import { describe, expect, it } from "vitest";
import { DEPENDENCY_TYPES, PROGRESSION_BANDS, REVISIT_TRIGGERS, SYNTHETIC_IDS, createSyntheticPlannerContext, evaluateCandidateEligibility, generateQuestionCandidates, planNextAction, progressionBandFor } from "@/lib/domain/conversation-intelligence";

const output={decision_id:"60000000-0000-4000-8000-000000000002",created_at:"2026-08-06T14:00:00.000Z"};
const item=(key:"room_type"|"building_type"|"indoor_unit_position_known"|"outdoor_unit_position_known"|"line_route_known"|"accessibility_known"|"electrical_supply_known",status:"answered"|"customer_does_not_know"|"customer_cannot_provide"|"skipped"|"deferred"|"requires_additional_evidence")=>({information_key:key,entity_type:key==="room_type"||key==="indoor_unit_position_known"?"room" as const:"project" as const,entity_id:key==="room_type"||key==="indoor_unit_position_known"?SYNTHETIC_IDS.room:SYNTHETIC_IDS.project,collection_status:status,last_answer_meaning:status==="answered"?(key==="indoor_unit_position_known"?"customer_can_provide" as const:"customer_knows" as const):status==="customer_does_not_know"?"customer_does_not_know" as const:status==="customer_cannot_provide"?"customer_cannot_provide" as const:status==="requires_additional_evidence"?"requires_additional_evidence" as const:"defer_collection" as const,attempts:1,evidence_requirement:status==="requires_additional_evidence"?"additional_evidence" as const:"none" as const,revisit_status:"allowed" as const,updated_at:output.created_at});
const withCollection=(items:readonly ReturnType<typeof item>[],extra={})=>createSyntheticPlannerContext(undefined,{information_collection_state:{project_id:SYNTHETIC_IDS.project,conversation_id:SYNTHETIC_IDS.conversation,version:items.length,items,updated_at:output.created_at},...extra});
const candidates=(context:ReturnType<typeof createSyntheticPlannerContext>)=>{const result=generateQuestionCandidates(context);if(!result.success)throw new Error(result.code);return result.data;};

describe("AP-15-04-01-05 kontrollierte Progression",()=>{
 it("hält Bänder, Dependency-Typen und Revisit-Trigger geschlossen und deterministisch",()=>{
  expect(PROGRESSION_BANDS).toEqual(["basic_need","room_context","placement_context","installation_context","technical_clarification"]);
  expect(DEPENDENCY_TYPES).toEqual(["hard","progression","contextual"]);expect(REVISIT_TRIGGERS).not.toContain("continuation");expect(REVISIT_TRIGGERS).not.toContain("time_elapsed");
  expect(progressionBandFor("room_type")).toBe("room_context");expect(progressionBandFor("line_route_known")).toBe("installation_context");expect(progressionBandFor("electrical_supply_known")).toBe("technical_clarification");
 });
 it("lässt Score Elektro nicht vor Raumkontext ziehen",()=>{const result=planNextAction(createSyntheticPlannerContext(),output);expect(result.success&&result.data.kind==="selected_action"&&result.data.action.progression_band).toBe("room_context");});
 it("modelliert Position, Route, Zugang und Elektro statisch",()=>{const all=candidates(createSyntheticPlannerContext());expect(all.find(c=>c.information_key==="indoor_unit_position_known")?.dependencies).toEqual(expect.arrayContaining([expect.objectContaining({information_key:"room_type",type:"progression"})]));expect(all.find(c=>c.information_key==="line_route_known")).toMatchObject({dependency_status:"not_satisfied",dependencies:[{information_key:"indoor_unit_position_known",type:"hard"},{information_key:"outdoor_unit_position_known",type:"hard"}]});expect(all.find(c=>c.information_key==="accessibility_known")?.dependencies[0]).toMatchObject({type:"hard"});expect(all.find(c=>c.information_key==="electrical_supply_known")?.dependencies[0]).toMatchObject({type:"progression"});});
 it("macht Route erst mit beiden Positionskontexten eligible",()=>{const initial=createSyntheticPlannerContext();const base=createSyntheticPlannerContext(undefined,{missing_information:initial.missing_information.filter(n=>n.information_key==="line_route_known")});const route=candidates(base).find(c=>c.information_key==="line_route_known")!;expect(evaluateCandidateEligibility(route,base)).toMatchObject({success:true,data:{eligible:false,codes:expect.arrayContaining(["dependency_not_satisfied"])} });const ready=withCollection([item("indoor_unit_position_known","answered"),item("outdoor_unit_position_known","answered")],{missing_information:initial.missing_information.filter(n=>n.information_key==="line_route_known")});const candidate=candidates(ready).find(c=>c.information_key==="line_route_known")!;expect(candidate.dependency_status).toBe("satisfied");expect(evaluateCandidateEligibility(candidate,ready)).toMatchObject({success:true,data:{eligible:true}});});
 it.each(["customer_does_not_know","customer_cannot_provide","skipped","deferred","requires_additional_evidence"] as const)("blockiert Collection-Status %s ohne neuen Pfad",status=>{const context=withCollection([item("outdoor_unit_position_known",status)]);const candidate=candidates(context).find(c=>c.information_key==="outdoor_unit_position_known")!;expect(candidate).toMatchObject({collection_eligibility:"blocked",revisit_status:"not_allowed"});expect(evaluateCandidateEligibility(candidate,context)).toMatchObject({success:true,data:{eligible:false,codes:expect.arrayContaining(["revisit_not_allowed"])} });});
 it("erlaubt Revisit ausschließlich mit explizitem kontrolliertem Trigger",()=>{const exhausted=item("line_route_known","requires_additional_evidence");const context=withCollection([exhausted],{revisit_triggers:[{information_key:"line_route_known",entity_id:SYNTHETIC_IDS.project,trigger:"new_dependency_information"}]});const candidate=candidates(context).find(c=>c.information_key==="line_route_known")!;expect(candidate).toMatchObject({collection_eligibility:"revisit_allowed",revisit_status:"trigger_present",reason_codes:["revisit_trigger_present"]});});
 it("aktiviert unbekannte Route nicht durch Innenposition, Intermediate oder Continue allein",()=>{const context=withCollection([item("line_route_known","requires_additional_evidence"),item("indoor_unit_position_known","answered"),item("outdoor_unit_position_known","answered")]);const route=candidates(context).find(c=>c.information_key==="line_route_known")!;expect(route.dependency_status).toBe("satisfied");expect(evaluateCandidateEligibility(route,context)).toMatchObject({success:true,data:{eligible:false,codes:expect.arrayContaining(["additional_evidence_required","revisit_not_allowed"])} });});
 it("bezeichnet einen echten Dead End nicht als Customer-Effort-Break",()=>{const blocked=withCollection([item("room_type","customer_does_not_know"),item("building_type","deferred"),item("indoor_unit_position_known","customer_does_not_know"),item("outdoor_unit_position_known","customer_does_not_know"),item("line_route_known","requires_additional_evidence"),item("accessibility_known","deferred"),item("electrical_supply_known","customer_does_not_know")],{missing_information:createSyntheticPlannerContext().missing_information.filter(n=>n.information_key!=="room_area_sqm")});expect(planNextAction(blocked,output)).toMatchObject({success:true,data:{kind:"stop_result",stop:{stop_reason:"no_eligible_customer_action",reason_codes:["no_eligible_customer_action"]}}});});
 it("mutiert weder Technical Knowledge noch Collection State",()=>{const context=withCollection([item("outdoor_unit_position_known","customer_does_not_know")]);const before=structuredClone(context);planNextAction(context,output);expect(context).toEqual(before);});
});
