import {describe,expect,it} from "vitest";
import {applyCustomerEffortOutcome,applyRetryOutcome,conversationCycleContextSchema,conversationCycleEventSchema,createSyntheticConversationCycleContext,deriveConversationEvents,interpretNormalizedAnswer,runConversationCycle} from "@/lib/domain/conversation-intelligence";

describe("pure conversation cycle",()=>{
 it("applies an answer, recalculates and renders the next action",()=>{const input=createSyntheticConversationCycleContext("exact");const frozen=JSON.stringify(input);const result=runConversationCycle(input);expect(result.success).toBe(true);if(!result.success)return;expect(result.current_state_version).toBe(2);expect(result.knowledge_state.claims.at(-1)).toMatchObject({property_key:"room_area_sqm",value:25,epistemic_status:"reported"});expect(result.retry_state.items[0]).toMatchObject({attempts:0,last_outcome:"answered"});expect(result.assessment.based_on_state_version).toBe(2);expect(result.planner_result.kind==="selected_action"?result.planner_result.action.based_on_state_version:result.planner_result.stop.based_on_state_version).toBe(2);expect(result.events.map(e=>e.sequence)).toEqual(result.events.map((_,i)=>100+i));expect(result.events.every(e=>conversationCycleEventSchema.safeParse(e).success)).toBe(true);expect(JSON.stringify(input)).toBe(frozen);});
 it("preserves approximation",()=>{const result=runConversationCycle(createSyntheticConversationCycleContext("approximate"));expect(result.success&&result.knowledge_state.claims.at(-1)?.value).toBe(25);});
 it("records unknown attempts and leaves information missing",()=>{const result=runConversationCycle(createSyntheticConversationCycleContext("unknown"));expect(result.success).toBe(true);if(!result.success)return;expect(result.retry_state.items[0]).toMatchObject({attempts:1,last_outcome:"unknown"});expect(result.missing_information).toEqual(expect.arrayContaining([expect.objectContaining({information_key:"room_area_sqm"})]));expect(result.events.some(e=>e.event_type==="answer_unknown_recorded")).toBe(true);});
 it("continues a skip without changing knowledge state",()=>{const result=runConversationCycle(createSyntheticConversationCycleContext("skipped"));expect(result.success).toBe(true);if(!result.success)return;expect(result.current_state_version).toBe(1);expect(result.cycle_status).toBe("no_state_change");expect(result.retry_state.items[0]).toMatchObject({attempts:1,last_outcome:"skipped"});expect(result.events.some(e=>e.event_type==="answer_skipped")).toBe(true);});
 it("handles confirmed and rejected assumptions",()=>{const confirmed=runConversationCycle(createSyntheticConversationCycleContext("assumption_confirmed"));const rejected=runConversationCycle(createSyntheticConversationCycleContext("assumption_rejected"));expect(confirmed.success&&confirmed.current_state_version).toBe(2);expect(confirmed.success&&confirmed.knowledge_state.claims.at(-1)?.epistemic_status).toBe("assumed");expect(rejected.success&&rejected.current_state_version).toBe(1);});
 it("fails closed for stale and processed cycles",()=>{const base=createSyntheticConversationCycleContext();const stale=runConversationCycle({...base,expected_state_version:2});expect(stale).toMatchObject({success:false,code:"cycle_state_version_mismatch",requires_replanning:true});const replay=runConversationCycle({...base,execution_status:"already_processed"});expect(replay).toMatchObject({success:false,code:"cycle_already_processed"});expect(base.knowledge_state.state_version).toBe(1);});
 it("validates retry uniqueness and caps attempts",()=>{const ctx=createSyntheticConversationCycleContext();const action=ctx.interpretation_inputs.selected_action;const one=applyRetryOutcome(ctx.retry_state,{...action,retry_outcome:"unknown",occurred_at:ctx.occurred_at});expect(one.success).toBe(true);if(!one.success)return;const two=applyRetryOutcome(one.state,{...action,retry_outcome:"unknown",occurred_at:ctx.occurred_at});const three=two.success?applyRetryOutcome(two.state,{...action,retry_outcome:"unknown",occurred_at:ctx.occurred_at}):two;expect(three.success&&three.state.items[0].attempts).toBe(2);expect(conversationCycleContextSchema.safeParse({...ctx,retry_state:{...ctx.retry_state,items:[...(one.state.items),...(one.state.items)]}}).success).toBe(false);});
 it("updates customer effort only from action contracts",()=>{const ctx=createSyntheticConversationCycleContext();const next=applyCustomerEffortOutcome(ctx.customer_effort_state,ctx.interpretation_inputs.selected_action,"unknown",true,ctx.occurred_at);expect(next).toMatchObject({consecutive_technical_questions:1,unanswered_questions:1,repeated_questions:1});});
 it("derives deterministic, PII-free events",()=>{const ctx=createSyntheticConversationCycleContext();const interpretation=interpretNormalizedAnswer({...ctx.interpretation_inputs,project_id:ctx.project_id,conversation_id:ctx.conversation_id,current_state_version:1,knowledge_state:ctx.knowledge_state,normalized_answer:ctx.normalized_answer});expect(interpretation.success).toBe(true);if(!interpretation.success)return;const applied={success:true as const,changed:true as const,code:"transition_applied" as const,apply_id:ctx.next_state_ids.apply_id,transition_id:interpretation.proposal.transition_id,interpretation_id:interpretation.proposal.interpretation_id,idempotency_key:interpretation.proposal.idempotency_key,previous_state_version:1,new_state_version:2,applied_transition_type:interpretation.proposal.transition_type,knowledge_state:{...ctx.knowledge_state,state_version:2},applied_claim_ids:[interpretation.proposal.claim_proposals[0].claim_id],superseded_claim_ids:[]};const args={interpretation,proposal:interpretation.proposal,apply_result:applied,event_ids:ctx.event_ids,sequence_start:100,occurred_at:ctx.occurred_at,correlation_id:ctx.correlation_id,result_code:"next_action_selected"};const a=deriveConversationEvents(args),b=deriveConversationEvents(args);expect(a).toEqual(b);expect(JSON.stringify(a)).not.toMatch(/email|phone|address|message_text|prompt|token/i);});
});
