import { describe, expect, it } from "vitest";
import { conversationRuntimeHeaderSchema, isPendingInteractionCurrent, materializeCollectionState, materializeEffortState, materializeRetryState, pendingInteractionSchema, validatePendingTemplateBinding } from "@/lib/domain/conversation-runtime";
import { canManageConversationRuntime } from "@/lib/domain/permissions";

const ids={conversation:"10000000-0000-4000-8000-000000000001",project:"10000000-0000-4000-8000-000000000002",interaction:"10000000-0000-4000-8000-000000000003",decision:"10000000-0000-4000-8000-000000000004",entity:"10000000-0000-4000-8000-000000000005"};
const at="2026-08-23T12:00:00.000Z";
const runtime={conversation_id:ids.conversation,project_id:ids.project,revision:2,knowledge_state_version:3,runtime_status:"awaiting_customer_answer",active_pending_interaction_id:ids.interaction,active_evidence_request_id:null,created_at:at,updated_at:at} as const;
const interaction={id:ids.interaction,conversation_id:ids.conversation,project_id:ids.project,decision_id:ids.decision,selected_action_type:"ask_approximate_number",information_key:"room_area_sqm",entity_type:"room",entity_id:ids.entity,template_key:"ask_room_area_approximate",template_version:1,locale:"de",answer_type:"approximate_number",expected_knowledge_state_version:3,runtime_revision:2,status:"pending",answered_by_message_id:null,created_at:at,answered_at:null,superseded_at:null,cancelled_at:null} as const;

describe("persistent conversation runtime contracts",()=>{
 it("keeps runtime mutation admin-only",()=>{expect(canManageConversationRuntime("admin")).toBe(true);expect(canManageConversationRuntime("reviewer")).toBe(false);expect(canManageConversationRuntime(null)).toBe(false)});
 it("strictly validates header/action exclusivity",()=>{expect(conversationRuntimeHeaderSchema.parse(runtime).revision).toBe(2);expect(conversationRuntimeHeaderSchema.safeParse({...runtime,provider_id:"x"}).success).toBe(false);expect(conversationRuntimeHeaderSchema.safeParse({...runtime,active_evidence_request_id:ids.decision}).success).toBe(false)});
 it("strictly binds pending interaction to the original registry contract",()=>{expect(pendingInteractionSchema.parse(interaction).decision_id).toBe(ids.decision);expect(validatePendingTemplateBinding(interaction)).toBe(true);expect(validatePendingTemplateBinding({...interaction,template_version:2})).toBe(false);expect(validatePendingTemplateBinding({...interaction,answer_type:"boolean"})).toBe(false)});
 it("fails closed for stale, future, inactive, or cross-bound answers",()=>{const input={interaction,runtime,conversation_id:ids.conversation,project_id:ids.project,current_knowledge_state_version:3};expect(isPendingInteractionCurrent(input)).toBe("current");expect(isPendingInteractionCurrent({...input,current_knowledge_state_version:4})).toBe("stale_knowledge_version");expect(isPendingInteractionCurrent({...input,interaction:{...interaction,expected_knowledge_state_version:4}})).toBe("future_knowledge_version");expect(isPendingInteractionCurrent({...input,runtime:{...runtime,active_pending_interaction_id:ids.decision}})).toBe("inactive_interaction")});
 it("roundtrips collection, retry and four-question effort without defaults",()=>{const item={information_key:"room_area_sqm",entity_type:"room",entity_id:ids.entity,collection_status:"customer_does_not_know",last_answer_meaning:"customer_does_not_know",attempts:2,evidence_requirement:"none",revisit_status:"allowed",last_collection_path:"customer_question",last_gain_reason:"retry_limit_reached",updated_at:at};const collection=materializeCollectionState(ids.project,ids.conversation,[{conversation_id:ids.conversation,project_id:ids.project,runtime_revision:2,collection_version:1,item}],at);expect(collection.items[0].last_answer_meaning).toBe("customer_does_not_know");const retry=materializeRetryState(ids.project,ids.conversation,[{conversation_id:ids.conversation,project_id:ids.project,runtime_revision:2,item:{information_key:"room_area_sqm",entity_type:"room",entity_id:ids.entity,attempts:2,last_outcome:"unknown",last_attempt_at:at}}],at);expect(retry.items[0].attempts).toBe(2);expect(materializeEffortState({conversation_id:ids.conversation,project_id:ids.project,runtime_revision:2,consecutive_technical_questions:4,unanswered_questions:1,repeated_questions:1}).consecutive_technical_questions).toBe(4)});
});
