import { describe, expect, it } from "vitest";
import {
  createDescriptiveClaimReviewState, descriptiveClaimReviewCommandSchema,
  descriptiveClaimReviewEntrySchema, deriveMissingInformation, deriveReadiness,
  fingerprintDescriptiveClaimProposal, reviewDescriptiveClaimProposal,
} from "@/lib/domain/conversation-intelligence";
import type { KnowledgeClaim, KnowledgeClaimProposal, KnowledgeState } from "@/lib/domain/conversation-intelligence";

const PROJECT="a1000000-0000-4000-8000-000000000001",CONVERSATION="a1000000-0000-4000-8000-000000000002",ENTITY="a1000000-0000-4000-8000-000000000003",ACTOR="a1000000-0000-4000-8000-000000000004",AT="2026-08-20T12:00:00.000Z";
const properties=["room_overview_context_observed","indoor_installation_area_observed","outdoor_installation_area_observed","line_route_context_observed","wall_penetration_context_observed"] as const;
const appliedClaim=(p:KnowledgeClaimProposal,patch:Record<string,unknown>={}):KnowledgeClaim=>{const {based_on_state_version:_,proposed_state_version:__,proposal_reason_codes:___,...claim}=p;return {...claim,created_at:AT,state_version:1,...patch} as KnowledgeClaim};
const state=(claims:readonly KnowledgeClaim[]=[]):KnowledgeState=>({project_id:PROJECT,conversation_id:CONVERSATION,state_version:1,claims,updated_at:AT});
const proposal=(property:typeof properties[number],overrides:Record<string,unknown>={}):KnowledgeClaimProposal=>({claim_id:`a2000000-0000-4000-8000-00000000000${properties.indexOf(property)+1}`,project_id:PROJECT,entity_type:property.startsWith("room_")||property.startsWith("indoor_")?"room":"installation",entity_id:ENTITY,property_key:property,value:true,value_type:"boolean",epistemic_status:"observed",knowledge_strength:"descriptive_fact",evidence:[{evidence_id:`a3000000-0000-4000-8000-00000000000${properties.indexOf(property)+1}`,source_type:"ai_analysis",source_id:`a4000000-0000-4000-8000-00000000000${properties.indexOf(property)+1}`,actor_class:"ai",observed_at:AT,evidence_status:"active"}],based_on_state_version:1,proposed_state_version:2,proposal_reason_codes:[],...overrides} as KnowledgeClaimProposal);
const command=(p:KnowledgeClaimProposal,action:"approve"|"reject"|"mark_evidence_insufficient"="approve",overrides:Record<string,unknown>={})=>({project_id:PROJECT,conversation_id:CONVERSATION,proposal_id:p.claim_id,expected_knowledge_state_version:1,review_action:action,review_actor_class:"admin",review_actor_id:ACTOR,reviewed_at:AT,...overrides});
const review=(p:KnowledgeClaimProposal,options:{current?:ReturnType<typeof state>;reviewState?:ReturnType<typeof createDescriptiveClaimReviewState>;action?:"approve"|"reject"|"mark_evidence_insufficient";command?:Record<string,unknown>}={})=>reviewDescriptiveClaimProposal({command:command(p,options.action,options.command),current_state:options.current??state(),review_state:options.reviewState??createDescriptiveClaimReviewState(PROJECT,CONVERSATION),proposals:[p],transition_id:"a5000000-0000-4000-8000-000000000001",apply_id:"a5000000-0000-4000-8000-000000000002"});

describe("AP-15-04-01-12-03-01 descriptive claim review",()=>{
  it("validiert den strict Admin-Reviewvertrag",()=>{const p=proposal(properties[0]);expect(descriptiveClaimReviewCommandSchema.safeParse(command(p)).success).toBe(true);expect(descriptiveClaimReviewCommandSchema.safeParse({...command(p),free_text:"ja"}).success).toBe(false);expect(descriptiveClaimReviewCommandSchema.safeParse(command(p,"approve",{review_action:"confirm"})).success).toBe(false);expect(descriptiveClaimReviewCommandSchema.safeParse(command(p,"approve",{review_actor_class:"ai"})).success).toBe(false);expect(descriptiveClaimReviewCommandSchema.safeParse(command(p,"approve",{review_actor_id:"admin"})).success).toBe(false);expect(descriptiveClaimReviewCommandSchema.safeParse(command(p,"approve",{reviewed_at:"heute"})).success).toBe(false);});
  it.each(properties)("übernimmt %s ausschließlich über eine N→N+1 Transition",property=>{const p=proposal(property);const result=review(p);expect(result).toMatchObject({code:"approved",changed:true,knowledge_state:{state_version:2},review_state:{revision:1},transition_proposal:{transition_type:"claim_created",superseded_claim_ids:[]}});expect(result.knowledge_state.claims.at(-1)).toMatchObject({property_key:property,value:true,value_type:"boolean",knowledge_strength:"descriptive_fact",epistemic_status:"observed"});expect(fingerprintDescriptiveClaimProposal(p)).toMatch(/^descriptive-v1:[0-9a-f]{8}$/);});
  it.each([["reject","rejected"],["mark_evidence_insufficient","insufficient_evidence"]] as const)("behandelt %s ohne Knowledge-Mutation",(action,code)=>{const p=proposal(properties[0]);const before=state();const result=review(p,{current:before,action});expect(result).toMatchObject({code,changed:false,knowledge_state:before,review_state:{revision:1}});expect(result.review_state).not.toBe(createDescriptiveClaimReviewState(PROJECT,CONVERSATION));expect(descriptiveClaimReviewEntrySchema.safeParse(result.review_state.entries[0]).success).toBe(true);});
  it("wendet CAS ohne stille Rebase an",()=>{const result=review(proposal(properties[0]),{command:{expected_knowledge_state_version:2}});expect(result).toMatchObject({code:"stale_state",changed:false,knowledge_state:{state_version:1},review_state:{revision:0}});});
  it("ist bei Replay idempotent und erzeugt keine zweite Revision",()=>{const p=proposal(properties[0]);const first=review(p);const second=review(p,{current:first.knowledge_state as ReturnType<typeof state>,reviewState:first.review_state});expect(second).toMatchObject({code:"already_applied",changed:false,knowledge_state:{state_version:2},review_state:{revision:1}});expect(second.knowledge_state.claims).toHaveLength(1);});
  it("erzeugt für einen äquivalenten Claim keinen Duplicate",()=>{const p=proposal(properties[2]);const existing=appliedClaim(p,{claim_id:"a6000000-0000-4000-8000-000000000001",evidence:[{...p.evidence[0],evidence_id:"a6000000-0000-4000-8000-000000000002"}]});const result=review(p,{current:state([existing])});expect(result).toMatchObject({code:"no_change",changed:false,knowledge_state:{state_version:1},review_state:{revision:1}});expect(result.knowledge_state.claims).toHaveLength(1);});
  it("schützt einen reviewer-gestützten Claim ohne Supersession",()=>{const p=proposal(properties[3]);const conflicting=appliedClaim(p,{claim_id:"a7000000-0000-4000-8000-000000000001",evidence:[{...p.evidence[0],evidence_id:"a7000000-0000-4000-8000-000000000002",source_type:"reviewer_correction",actor_class:"reviewer",evidence_status:"active"}]});const result=review(p,{current:state([conflicting])});expect(result).toMatchObject({code:"no_change",changed:false,knowledge_state:{state_version:1},review_state:{revision:1}});expect(result.transition_proposal).toBeUndefined();expect(result.knowledge_state.claims).toHaveLength(1);});
  it("lässt AI vorschlagen, aber weder AI noch Customer reviewen",()=>{const p=proposal(properties[1]);expect(review(p).code).toBe("approved");expect(review(p,{command:{review_actor_class:"ai"}}).code).toBe("invalid_review_context");expect(review(p,{command:{review_actor_class:"customer"}}).code).toBe("invalid_review_context");});
  it("schreibt Strength, Epistemik oder falsche Werte niemals um",()=>{for(const patch of [{knowledge_strength:"technical_assessment"},{epistemic_status:"confirmed"},{value:false},{value_type:"string"}])expect(review(proposal(properties[0],patch))).toMatchObject({code:"invalid_review_context",changed:false});});
  it("lässt Readiness und Technical Missing Information exakt unverändert",()=>{const p=proposal(properties[2]);const before=state();const readiness=deriveReadiness(before);const missing=deriveMissingInformation(before);const result=review(p,{current:before});expect(deriveReadiness(result.knowledge_state)).toEqual(readiness);expect(deriveMissingInformation(result.knowledge_state)).toEqual(missing);expect(result.knowledge_state.claims.some(claim=>claim.property_key==="outdoor_unit_position_known")).toBe(false);});
  it("rekonstruiert deterministisch und mutiert Eingaben nicht",()=>{const p=proposal(properties[4]);const before=state(),reviews=createDescriptiveClaimReviewState(PROJECT,CONVERSATION);const a=review(p,{current:before,reviewState:reviews}),b=review(p,{current:before,reviewState:reviews});expect(a).toEqual(b);expect(before.claims).toEqual([]);expect(reviews).toEqual({project_id:PROJECT,conversation_id:CONVERSATION,revision:0,entries:[]});});
});
