import {describe,expect,it} from "vitest";
import {createSimulatorStart,executeSimulatorAnswer,executeSimulatorContinuation,executeSimulatorEvidenceResponse,resolveSyntheticEvidenceRequest,type ConversationCycleContext,type ConversationCycleResult} from "@/lib/domain/conversation-intelligence";

const answer=(context:ConversationCycleContext)=>{const interaction=context.interpretation_inputs.rendered_interaction;return interaction.answer_contract?.answer_type==="boolean"?{kind:"option" as const,option_key:"unknown"}:{kind:"text" as const,value:interaction.template_key==="ask_room_area_approximate"?"25 m²":interaction.template_key==="ask_building_type"?"Einfamilienhaus":"Wohnzimmer"};};
function reachEvidence(){let context=createSimulatorStart("empty_synthetic_project");let previous:ConversationCycleResult|undefined;for(let cycle=1;cycle<30;cycle++){const execution=executeSimulatorAnswer(context,answer(context),cycle);previous=execution.result;if(previous?.success&&previous.cycle_status==="evidence_request_selected")return{context:execution.next??context,result:previous,cycle};if(execution.next){context=execution.next;continue;}if(previous?.success&&previous.cycle_status==="intermediate_result_ready"){const continued=executeSimulatorContinuation(context,previous,cycle+100);if(continued.next){context=continued.next;continue;}}break;}throw new Error(`evidence_not_reached:${JSON.stringify(previous)}`);}

describe("AP-15-04-01-08 Evidence Request Conversation Orchestration",()=>{
 it("integriert future_photo_request als eigenen Cycle-Status",()=>{const {result}=reachEvidence();expect(result.cycle_status).toBe("evidence_request_selected");expect(result.selected_evidence_request).toBeDefined();expect(result.rendered_evidence_request?.heading).toBe("Foto benötigt");expect(result.evidence_request_state.requests.at(-1)?.status).toBe("requested");});
 it.each(["provided","declined","skipped"] as const)("verarbeitet %s ohne Knowledge- oder Readiness-Fortschritt",outcome=>{const reached=reachEvidence();const beforeKnowledge=reached.result.knowledge_state;const beforeReadiness=reached.result.readiness;const response=executeSimulatorEvidenceResponse(reached.context,reached.result,{kind:"evidence_response",request_id:reached.result.selected_evidence_request!.request_id,outcome},reached.cycle+1);expect(response.result.success).toBe(true);if(!response.result.success)return;expect(response.result.knowledge_state).toEqual(beforeKnowledge);expect(response.result.readiness).toEqual(beforeReadiness);expect(response.result.evidence_request_state.requests.at(-1)?.status).toBe(outcome);expect(response.result.missing_information).toEqual(reached.result.missing_information);if(outcome==="provided")expect(response.result.evidence_availability.at(-1)?.status).toBe("available_unanalysed");});
 it("weist inaktive, bereits gelöste und ungültige Responses geschlossen ab",()=>{const reached=reachEvidence();expect(resolveSyntheticEvidenceRequest(reached.result.evidence_request_state,"94000000-0000-4000-8000-000000000099","provided","2026-08-11T12:00:00.000Z")).toMatchObject({success:false,code:"evidence_request_not_active"});const first=resolveSyntheticEvidenceRequest(reached.result.evidence_request_state,reached.result.selected_evidence_request!.request_id,"skipped","2026-08-11T12:00:00.000Z");expect(resolveSyntheticEvidenceRequest(first.state,reached.result.selected_evidence_request!.request_id,"provided","2026-08-11T12:01:00.000Z")).toMatchObject({success:false,code:"evidence_request_already_resolved"});expect(resolveSyntheticEvidenceRequest({},"bad","invalid","bad")).toMatchObject({success:false,code:"evidence_response_invalid"});});
});
