import {describe,expect,it} from "vitest";
import {DOCUMENT_EVIDENCE_TARGET_REGISTRY,EVIDENCE_BUNDLE_REGISTRY,EVIDENCE_PURPOSE_CODES,EVIDENCE_REQUEST_ACTION_TYPES,EVIDENCE_REQUEST_TEMPLATES,EVIDENCE_SIMULATOR_CONTROLS,EVIDENCE_TARGET_REGISTRY,EVIDENCE_TARGET_KEYS,INFORMATION_KEY_EVIDENCE_TARGETS,appendPlannedEvidenceRequest,evidenceRequestStateSchema,planEvidenceRequest,resolveSyntheticEvidenceRequest,selectedEvidenceRequestSchema,type EvidencePlanningNeed} from "@/lib/domain/conversation-intelligence";
import {SYNTHETIC_IDS} from "@/lib/domain/conversation-intelligence";

const requestId="94000000-0000-4000-8000-000000000001", at="2026-08-11T10:00:00.000Z";
const state=()=>({project_id:SYNTHETIC_IDS.project,conversation_id:SYNTHETIC_IDS.conversation,requests:[] as const,revision:0});
const need=(information_key:"indoor_unit_position_known"|"outdoor_unit_position_known"|"line_route_known"|"electrical_supply_known"|"accessibility_known"|"room_area_sqm",entity_type:"room"|"installation"="installation"):EvidencePlanningNeed=>({information_key,entity_type,entity_id:SYNTHETIC_IDS.project,open:true,collection_path:"future_photo_request"});
const input=(needs= [need("outdoor_unit_position_known")],overrides:Record<string,unknown>={})=>({project_id:SYNTHETIC_IDS.project,conversation_id:SYNTHETIC_IDS.conversation,request_id:requestId,needs,request_state:state(),availability:[],available_dependency_keys:["building_type"] as const,human_review_required:false,site_check_authoritative:false,consecutive_evidence_requests:0,total_evidence_requests:0,...overrides});

describe("AP-15-04-01-07 Controlled Evidence Request Planner",()=>{
 it("hält Actions, Targets, Purpose und Schemas geschlossen",()=>{expect(EVIDENCE_REQUEST_ACTION_TYPES).toEqual(["request_photo","request_multiple_photos","request_document","no_evidence_request"]);expect(new Set(EVIDENCE_TARGET_KEYS).size).toBe(EVIDENCE_TARGET_KEYS.length);expect(EVIDENCE_PURPOSE_CODES).toContain("evaluate_electrical_context");expect(evidenceRequestStateSchema.safeParse({...state(),extra:true}).success).toBe(false);expect(selectedEvidenceRequestSchema.safeParse({}).success).toBe(false)});
 it("stellt eine tief eingefrorene statische Registry und explizites Mapping bereit",()=>{expect(Object.isFrozen(EVIDENCE_TARGET_REGISTRY)).toBe(true);expect(Object.isFrozen(EVIDENCE_TARGET_REGISTRY[0].supports_information_keys)).toBe(true);expect(EVIDENCE_TARGET_REGISTRY.filter(t=>t.status==="active").map(t=>t.target_key)).toEqual(["room_overview","indoor_area_overview","outdoor_area_overview","line_route_context","electrical_area","accessibility_context"]);expect(INFORMATION_KEY_EVIDENCE_TARGETS.outdoor_unit_position_known).toEqual(["outdoor_area_overview","outdoor_unit_location"])});
 it.each([["outdoor_unit_position_known","outdoor_area_overview",["building_type"]],["indoor_unit_position_known","indoor_area_overview",["room_type"]],["line_route_known","line_route_context",["indoor_unit_position_known","outdoor_unit_position_known"]],["electrical_supply_known","electrical_area",[]],["accessibility_known","accessibility_context",["indoor_unit_position_known"]]] as const)("plant %s kontrolliert",(key,target,deps)=>{const result=planEvidenceRequest(input([need(key)],{available_dependency_keys:deps}));expect(result).toMatchObject({kind:"evidence_request_selected",request:{action_type:"request_photo",target_key:target}})});
 it("nutzt ein Target für mehrere offene Needs",()=>{const result=planEvidenceRequest(input([need("outdoor_unit_position_known"),need("accessibility_known")],{available_dependency_keys:["building_type"]}));expect(result).toMatchObject({kind:"evidence_request_selected",request:{target_key:"outdoor_area_overview",information_keys:["outdoor_unit_position_known","accessibility_known"],request_reason_codes:expect.arrayContaining(["covers_multiple_needs"])}})});
 it("erlaubt nur kontrollierte Bundles",()=>{expect(EVIDENCE_BUNDLE_REGISTRY.map(b=>b.bundle_key)).toEqual(["indoor_context_bundle","outdoor_context_bundle","installation_route_bundle"]);const result=planEvidenceRequest(input([need("room_area_sqm","room"),need("indoor_unit_position_known")],{available_dependency_keys:["room_type"]}));expect(result).toMatchObject({kind:"evidence_request_selected",request:{action_type:"request_multiple_photos",bundle_key:"indoor_context_bundle"}})});
 it("blockiert falschen Pfad, Dependencies, Human Review, Site Check und Effort",()=>{expect(planEvidenceRequest(input([{...need("electrical_supply_known"),collection_path:"site_check"}]))).toMatchObject({kind:"no_evidence_request",reason:"collection_path_not_eligible"});expect(planEvidenceRequest(input([need("line_route_known")],{available_dependency_keys:[]}))).toMatchObject({kind:"no_evidence_request",reason:"dependency_not_satisfied"});expect(planEvidenceRequest(input(undefined,{human_review_required:true}))).toMatchObject({reason:"human_review_required"});expect(planEvidenceRequest(input(undefined,{site_check_authoritative:true}))).toMatchObject({reason:"site_check_authoritative"});expect(planEvidenceRequest(input(undefined,{consecutive_evidence_requests:2}))).toMatchObject({reason:"request_limit_reached"})});
 it("dedupliziert offene, abgelehnte und bereits vorhandene Evidence",()=>{const selected=planEvidenceRequest(input());if(selected.kind!=="evidence_request_selected")throw new Error("fixture");const requested=appendPlannedEvidenceRequest(state(),selected.request,at);expect(planEvidenceRequest(input(undefined,{request_state:requested}))).toMatchObject({kind:"no_evidence_request",reason:"duplicate_request"});const declined=resolveSyntheticEvidenceRequest(requested,requestId,"declined",at).state;expect(planEvidenceRequest(input(undefined,{request_state:declined}))).toMatchObject({reason:"duplicate_request"});expect(planEvidenceRequest(input(undefined,{availability:[{target_key:"outdoor_area_overview",status:"available_unanalysed",request_id:requestId}]}))).toMatchObject({reason:"duplicate_request"})});
 it("simuliert provided nur als unanalysierte Verfügbarkeit und verändert kein Knowledge",()=>{const selected=planEvidenceRequest(input());if(selected.kind!=="evidence_request_selected")throw new Error("fixture");const requested=appendPlannedEvidenceRequest(state(),selected.request,at);const knowledge={claims:[],state_version:1};const result=resolveSyntheticEvidenceRequest(requested,requestId,"provided",at);expect(result.availability?.status).toBe("available_unanalysed");expect(knowledge).toEqual({claims:[],state_version:1});expect(result.state.requests[0].status).toBe("provided")});
 it("liefert sichere deutsche Templates und reine Simulatorcontrols",()=>{const text=Object.values(EVIDENCE_REQUEST_TEMPLATES).join(" ").toLowerCase();expect(text).toContain("bitte nichts öffnen oder verändern");expect(text).toContain("keine leiter");expect(text).not.toMatch(/steig(?:e|en).*dach|sicherung.*entfern|gerät.*auseinander|fassade.*besteig/);expect(EVIDENCE_SIMULATOR_CONTROLS).toEqual(["Foto als vorhanden simulieren","Kann ich nicht liefern","Überspringen"])});
 it("hält Dokumentanforderungen deferred",()=>{expect(DOCUMENT_EVIDENCE_TARGET_REGISTRY).toHaveLength(0);expect(planEvidenceRequest(input([{...need("outdoor_unit_position_known"),collection_path:"future_document_request"}]))).toMatchObject({reason:"document_request_deferred"})});
});
