import {describe,expect,it} from "vitest";
import {COLLECTION_PATHS,INFORMATION_GAIN_REASON_CODES,INFORMATION_GAIN_STATUSES,SYNTHETIC_IDS,assessInformationGain,hasRelevantDependencyDelta,informationGainAssessmentInputSchema,informationGainAssessmentSchema} from "@/lib/domain/conversation-intelligence";

const channels={customer_question:true,customer_clarification:false,existing_evidence:false,future_photo_request:false,future_document_request:false,assumption:false,site_check:false,human_review:false};
const input=(overrides:Record<string,unknown>={})=>({project_id:SYNTHETIC_IDS.project,conversation_id:SYNTHETIC_IDS.conversation,information_key:"outdoor_unit_position_known" as const,entity_type:"installation" as const,entity_id:SYNTHETIC_IDS.project,knowledge_state_version:1,collection_state_version:0,attempts:0,collection_status:"not_asked" as const,dependency_signature:{},available_evidence_channels:channels,...overrides});

describe("AP-15-04-01-06 Information Gain",()=>{
 it("hält Status, Pfade und Gründe geschlossen und Schemas strikt",()=>{expect(INFORMATION_GAIN_STATUSES).toHaveLength(8);expect(COLLECTION_PATHS).toContain("future_photo_request");expect(INFORMATION_GAIN_REASON_CODES).toContain("same_context_as_previous_attempt");expect(informationGainAssessmentInputSchema.safeParse({...input(),extra:true}).success).toBe(false);expect(informationGainAssessmentSchema.safeParse({...assessInformationGain(input()),gain_status:"likely"}).success).toBe(false)});
 it("bewertet den ersten Versuch deterministisch und immutable",()=>{const value=input(),before=structuredClone(value);expect(assessInformationGain(value)).toEqual(assessInformationGain(value));expect(value).toEqual(before);expect(assessInformationGain(value)).toMatchObject({gain_status:"new_information_expected",preferred_collection_path:"customer_question",revisit_allowed:false,reason_codes:["new_information_expected"]})});
 it.each(["customer_does_not_know","customer_cannot_provide","skipped","requires_additional_evidence"] as const)("blockiert identische Frage bei %s",collection_status=>expect(assessInformationGain(input({attempts:1,collection_status,last_answer_meaning:collection_status==="skipped"?"defer_collection":collection_status}))).toMatchObject({preferred_collection_path:"leave_open",revisit_allowed:false,reason_codes:expect.arrayContaining(["same_context_as_previous_attempt"])}));
 it("erhält den alternativen Raumgrößen-Retry",()=>expect(assessInformationGain(input({information_key:"room_area_sqm",entity_type:"room",attempts:1,collection_status:"asked",last_answer_meaning:"leave_information_open",available_evidence_channels:{...channels,customer_clarification:true}}))).toMatchObject({preferred_collection_path:"customer_clarification",reason_codes:["alternate_question_strategy"]}));
 it("erkennt nur kontrollierte unavailable-zu-available Dependency-Deltas",()=>{expect(hasRelevantDependencyDelta({indoor_unit_position_known:"unavailable",outdoor_unit_position_known:"unavailable"},{indoor_unit_position_known:"available",outdoor_unit_position_known:"unavailable"})).toBe(true);expect(hasRelevantDependencyDelta({indoor_unit_position_known:"available"},{indoor_unit_position_known:"available"})).toBe(false)});
 it("fordert für den Leitungsweg beide neuen Positionskontexte",()=>{const common={information_key:"line_route_known",attempts:1,collection_status:"requires_additional_evidence",last_answer_meaning:"requires_additional_evidence",last_dependency_signature:{indoor_unit_position_known:"unavailable",outdoor_unit_position_known:"unavailable"},revisit_trigger:"new_dependency_information",available_evidence_channels:{...channels,customer_clarification:true}} as const;expect(assessInformationGain(input({...common,dependency_signature:{indoor_unit_position_known:"available",outdoor_unit_position_known:"unavailable"}}))).toMatchObject({revisit_allowed:false});expect(assessInformationGain(input({...common,dependency_signature:{indoor_unit_position_known:"available",outdoor_unit_position_known:"available"}}))).toMatchObject({gain_status:"context_changed",revisit_allowed:true,reason_codes:["dependency_context_changed"]})});
 it("macht Continue oder Intermediate allein niemals zum Gain-Grund",()=>expect(assessInformationGain(input({attempts:1,collection_status:"customer_does_not_know",last_answer_meaning:"customer_does_not_know",revisit_trigger:"post_intermediate_progression",available_evidence_channels:{...channels,customer_clarification:true}}))).toMatchObject({revisit_allowed:false,preferred_collection_path:"leave_open"}));
 it("modelliert Foto, Site Check und Dead End ohne Human-Review-Fallback",()=>{const exhausted={attempts:1,collection_status:"customer_does_not_know",last_answer_meaning:"customer_does_not_know"};expect(assessInformationGain(input({...exhausted,available_evidence_channels:{...channels,future_photo_request:true}}))).toMatchObject({preferred_collection_path:"future_photo_request"});expect(assessInformationGain(input({...exhausted,available_evidence_channels:{...channels,site_check:true}}))).toMatchObject({preferred_collection_path:"site_check"});expect(assessInformationGain(input(exhausted))).toMatchObject({preferred_collection_path:"leave_open"})});
 it("lässt einen Revisit das Limit von zwei Attempts nicht umgehen",()=>expect(assessInformationGain(input({attempts:2,collection_status:"requires_additional_evidence",revisit_trigger:"new_customer_evidence",available_evidence_channels:{...channels,customer_clarification:true,site_check:true}}))).toMatchObject({revisit_allowed:false,gain_status:"collection_complete_for_channel",preferred_collection_path:"site_check"}));
 it("bewertet einen bereits bestätigten identischen Fotokontext nicht als neuen Gain",()=>{const evidence_context=[{context_key:"outdoor_installation_area" as const,property_key:"outdoor_installation_area_observed" as const,entity_type:"installation" as const,entity_id:SYNTHETIC_IDS.installation,covered_target_keys:["outdoor_area_overview" as const]}];const value=input({attempts:1,collection_status:"requires_additional_evidence",last_answer_meaning:"requires_additional_evidence",evidence_target_key:"outdoor_area_overview",evidence_context,available_evidence_channels:{...channels,future_photo_request:true}});expect(assessInformationGain(value)).toMatchObject({gain_status:"customer_path_exhausted",preferred_collection_path:"leave_open",revisit_allowed:false,reason_codes:expect.arrayContaining(["existing_descriptive_evidence_context"])});expect(assessInformationGain(value)).toEqual(assessInformationGain(value));});
});
