import { describe, expect, it } from "vitest";
import {
  OBSERVATION_CLAIM_MAPPING_REGISTRY, OBSERVATION_REVIEW_CLASSES, SITE_CHECK_ONLY_BOUNDARIES,
  assessObservationClaimSufficiency, createEvidenceObservationState, deriveMissingInformation, deriveReadiness,
  observationClaimMappingResultSchema, observationClaimMappingRuleSchema, observationReviewClassSchema,
  observationSufficiencySchema, proposeKnowledgeClaimFromObservation,
} from "@/lib/domain/conversation-intelligence";

const PROJECT="91000000-0000-4000-8000-000000000001",CONVERSATION="91000000-0000-4000-8000-000000000002",ENTITY="91000000-0000-4000-8000-000000000003",REQUEST="91000000-0000-4000-8000-000000000004",EVIDENCE="91000000-0000-4000-8000-000000000005";
const state={project_id:PROJECT,conversation_id:CONVERSATION,state_version:1,claims:[],updated_at:"2026-08-20T12:00:00.000Z"} as const;
const targetByType:Record<string,string>={window_visible:"room_overview",door_visible:"room_overview",wall_area_visible:"room_overview",possible_indoor_mounting_area_visible:"indoor_area_overview",possible_outdoor_mounting_area_visible:"outdoor_area_overview",line_route_context_visible:"line_route_context",electrical_connection_visible:"electrical_area",accessibility_context_visible:"accessibility_context",wall_penetration_context_visible:"line_route_context",image_insufficient:"room_overview"};
const observation=(type:string,overrides:Record<string,unknown>={})=>({observation_id:"92000000-0000-4000-8000-000000000001",contract_version:1,evidence_id:EVIDENCE,project_id:PROJECT,conversation_id:CONVERSATION,target_key:targetByType[type],observation_category:"observation",observation_type:type,observation_value:type.startsWith("image_")?{kind:"evidence_condition",value:null}:{kind:"visibility",value:"visible"},source_actor_class:"admin",observed_at:"2026-08-20T12:00:00.000Z",evidence_quality:type==="image_insufficient"?"insufficient":"sufficient_for_observation",interpretation_status:type==="image_insufficient"?"insufficient":"observed",scope:{request_id:REQUEST,scope_key:"requested_target"},reason_codes:[type==="image_insufficient"?"insufficient_view":"visible_feature_recorded"],...overrides});
const map=(type:string,overrides:Record<string,unknown>={})=>proposeKnowledgeClaimFromObservation({observations:[observation(type,overrides)],project_id:PROJECT,conversation_id:CONVERSATION,entity_type:["window_visible","door_visible","wall_area_visible","possible_indoor_mounting_area_visible","image_insufficient"].includes(type)?"room":"installation",entity_id:ENTITY,knowledge_state:state,proposal_ids:{claim_id:"93000000-0000-4000-8000-000000000001",evidence_id:"93000000-0000-4000-8000-000000000002"},occurred_at:"2026-08-20T12:00:00.000Z"});

describe("AP-15-04-01-11 Observation-to-Claim Mapping",()=>{
  it("hält Schemas, Review Classes und Resultate strikt geschlossen",()=>{expect(OBSERVATION_REVIEW_CLASSES).toEqual(["auto_observable","auto_proposable","human_review_required","site_check_only"]);expect(observationReviewClassSchema.safeParse("review_if_confident").success).toBe(false);expect(observationSufficiencySchema.safeParse({kind:"observation_only",reason_codes:["descriptive_observation_only"],text:"frei"}).success).toBe(false);expect(observationClaimMappingRuleSchema.safeParse({...OBSERVATION_CLAIM_MAPPING_REGISTRY[0],extra:true}).success).toBe(false);expect(observationClaimMappingResultSchema.safeParse({...map("window_visible"),free_reason:"x"}).success).toBe(false);});
  it("ist tief immutable, eindeutig und referenziert nur gültige statische Semantik",()=>{expect(Object.isFrozen(OBSERVATION_CLAIM_MAPPING_REGISTRY)).toBe(true);expect(OBSERVATION_CLAIM_MAPPING_REGISTRY.every(rule=>Object.isFrozen(rule)&&Object.isFrozen(rule.allowed_source_actors)&&rule.allowed_source_actors.length>0)).toBe(true);expect(new Set(OBSERVATION_CLAIM_MAPPING_REGISTRY.map(rule=>rule.rule_key)).size).toBe(OBSERVATION_CLAIM_MAPPING_REGISTRY.length);expect(OBSERVATION_CLAIM_MAPPING_REGISTRY.every(rule=>observationClaimMappingRuleSchema.safeParse(rule).success)).toBe(true);expect(OBSERVATION_CLAIM_MAPPING_REGISTRY.filter(rule=>rule.review_class==="auto_proposable")).toHaveLength(0);});
  it.each(["window_visible","door_visible","wall_area_visible"])("lässt %s bewusst als reine Observation",type=>expect(map(type)).toMatchObject({kind:"observation_only",causes_state_change:false,application_status:"not_applied"}));
  it("verhindert verlustbehaftete Placement-, Route- und Accessibility-Ableitungen",()=>{expect(map("possible_indoor_mounting_area_visible")).toMatchObject({kind:"human_review_required"});expect(map("possible_outdoor_mounting_area_visible")).toMatchObject({kind:"human_review_required"});expect(map("line_route_context_visible")).toMatchObject({kind:"observation_only"});expect(map("accessibility_context_visible")).toMatchObject({kind:"observation_only"});for(const result of [map("possible_outdoor_mounting_area_visible"),map("line_route_context_visible"),map("accessibility_context_visible")])expect(result.kind).not.toBe("claim_proposal");});
  it("erzwingt Elektro- und Kernbohrungsgrenzen unabhängig vom Actor",()=>{for(const actor of ["admin","reviewer","ai"]){expect(map("electrical_connection_visible",{source_actor_class:actor})).toMatchObject({kind:"site_check_required",reason_codes:["electrical_suitability_site_check_only"]});expect(map("wall_penetration_context_visible",{source_actor_class:actor})).toMatchObject({kind:"site_check_required",reason_codes:["core_drilling_safety_site_check_only"]});}expect(SITE_CHECK_ONLY_BOUNDARIES).toEqual(expect.arrayContaining(["electrical_suitability","core_drilling_safety","hidden_services","structural_safety","legal_noise_assessment","final_mounting_approval"]));});
  it("blockiert insufficient, ambiguous und wrong target ohne positiven Proposal",()=>{expect(map("image_insufficient")).toMatchObject({kind:"insufficient_evidence"});expect(map("window_visible",{evidence_quality:"ambiguous",interpretation_status:"ambiguous"})).toMatchObject({kind:"insufficient_evidence",requires_human_review:true});expect(map("window_visible",{target_key:"electrical_area"})).toMatchObject({kind:"unsupported_mapping"});});
  it("erkennt Observation-Konflikte ohne Quality-Hierarchie",()=>{const first=observation("window_visible"),second=observation("window_visible",{observation_id:"92000000-0000-4000-8000-000000000002",observation_value:{kind:"visibility",value:"not_visible"}});const result=proposeKnowledgeClaimFromObservation({observations:[first,second],project_id:PROJECT,conversation_id:CONVERSATION,entity_type:"room",entity_id:ENTITY,knowledge_state:state,proposal_ids:{claim_id:"93000000-0000-4000-8000-000000000001",evidence_id:"93000000-0000-4000-8000-000000000002"},occurred_at:"2026-08-20T12:00:00.000Z"});expect(result).toMatchObject({kind:"conflicting_observations",requires_human_review:true});});
  it("ist deterministisch, verwendet injizierte IDs und verändert State, Readiness oder Missing Information nicht",()=>{const before=structuredClone(state),readiness=deriveReadiness(state),missing=deriveMissingInformation(state);expect(map("window_visible")).toEqual(map("window_visible"));expect(state).toEqual(before);expect(deriveReadiness(state)).toEqual(readiness);expect(deriveMissingInformation(state)).toEqual(missing);expect(createEvidenceObservationState(PROJECT,CONVERSATION).revision).toBe(0);});
  it("bewertet Sufficiency rein und fordert Sets nur bei expliziter Rule",()=>{const rule=OBSERVATION_CLAIM_MAPPING_REGISTRY.find(item=>item.observation_type==="window_visible")!;expect(assessObservationClaimSufficiency([observation("window_visible") as never],rule,"ai")).toMatchObject({kind:"observation_only"});expect(rule.requires_observation_set).toBeUndefined();});
});
