import { describe, expect, it } from "vitest";
import { createProjectMediaUploadTicketWithDataSource, type UploadTicketDataSource, type UploadTicketReservation } from "@/lib/actions/project-media-upload-ticket-service";
const project="11111111-1111-4111-8111-111111111111", media="22222222-2222-4222-8222-222222222222", user="33333333-3333-4333-8333-333333333333", stored="44444444-4444-4444-8444-444444444444.jpg";
const row:UploadTicketReservation={id:media,project_id:project,storage_bucket:"project-media",storage_path:`projects/${project}/originals/${media}/${stored}`,stored_filename:stored,mime_type:"image/jpeg",file_size_bytes:100,uploaded_by:user,upload_status:"pending",deleted_at:null};
function setup(change:Partial<UploadTicketReservation>={}, opt:{auth?:boolean;role?:string;active?:boolean;missing?:boolean}={}){const calls:unknown[][]=[];const source:UploadTicketDataSource={auth:{getUser:async()=>({data:{user:opt.auth===false?null:{id:user}}})},getProfile:async()=>({data:{role:opt.role??"admin"},error:null}),getActiveProject:async()=>({data:opt.active===false?null:{id:project},error:null}),getReservation:async()=>({data:opt.missing?null:{...row,...change},error:null}),createSignedUploadTicket:async(...args)=>{calls.push(args);return{data:{path:{...row,...change}.storage_path,token:"ticket"},error:null}}};return{source,calls};}
const input={media_id:media,project_id:project};
describe("Uploadticket",()=>{
 it.each([[{auth:false},"not_authenticated"],[{role:"reviewer"},"not_authorized"],[{active:false},"invalid_reservation"],[{missing:true},"invalid_reservation"]] as const)("weist Identität, Rolle, Projekt und fehlende Reservierung ab",async(opt,code)=>{const r=await createProjectMediaUploadTicketWithDataSource(setup({},opt).source,input);expect(r.success?"ok":r.code).toBe(code)});
 it.each([{project_id:crypto.randomUUID()},{uploaded_by:crypto.randomUUID()},{deleted_at:"x"},{upload_status:"ready"},{upload_status:"failed"},{storage_bucket:"other"},{mime_type:"text/plain"},{storage_path:"arbitrary"}])("weist manipulierte Reservierungen ab",async(change)=>{const r=await createProjectMediaUploadTicketWithDataSource(setup(change).source,input);expect(r.success).toBe(false)});
 it("bindet das Ticket an Bucket und Pfad der pending Reservierung und antwortet schmal",async()=>{const {source,calls}=setup();const r=await createProjectMediaUploadTicketWithDataSource(source,input);expect(calls).toEqual([[row.storage_bucket,row.storage_path]]);expect(r).toEqual({success:true,data:{media_id:media,project_id:project,path:row.storage_path,token:"ticket",expected_mime:"image/jpeg",expected_size:100}})});
 it("akzeptiert keine Clientfelder",async()=>{const r=await createProjectMediaUploadTicketWithDataSource(setup().source,{...input,path:"evil",bucket:"evil"});expect(r.success).toBe(false)});
});
