import { readFileSync } from "node:fs";
import { describe, expect, it, vi } from "vitest";
import { getProjectEvidenceWithDataSource, type ProjectEvidenceReadDataSource } from "@/lib/actions/project-evidence-read-service";
import type { ProjectEvidenceRow } from "@/lib/actions/project-evidence-binding-service";
const PROJECT="11111111-1111-4111-8111-111111111111", MEDIA="22222222-2222-4222-8222-222222222222";
const row:ProjectEvidenceRow={id:"33333333-3333-4333-8333-333333333333",project_id:PROJECT,project_media_id:MEDIA,evidence_target:"room_overview",purpose:"evaluate_room_dimension_context",source_channel:"internal_upload",source_actor_class:"admin",binding_status:"bound",created_at:"2026-08-21T12:00:00.000Z"};
function source(role="admin", rows: ProjectEvidenceRow[]=[row]):ProjectEvidenceReadDataSource{return{auth:{getUser:vi.fn().mockResolvedValue({data:{user:{id:"user"}}})},getProfile:vi.fn().mockResolvedValue({data:{role},error:null}),getActiveProject:vi.fn().mockResolvedValue({data:{id:PROJECT},error:null}),listEvidence:vi.fn().mockResolvedValue({data:rows,error:null})};}
describe("projektweiter Evidence-Read",()=>{
 it("ist admin-only, projektbezogen und lädt alle Bindings in genau einem Read",async()=>{const data=source();const result=await getProjectEvidenceWithDataSource(data,PROJECT);expect(result.success&&result.data.by_media_id[MEDIA]).toHaveLength(1);expect(data.listEvidence).toHaveBeenCalledOnce();expect(data.listEvidence).toHaveBeenCalledWith(PROJECT);expect((await getProjectEvidenceWithDataSource(source("reviewer"),PROJECT))).toMatchObject({success:false,code:"not_authorized"});});
 it("liefert ausschließlich das schmale locator- und PII-freie DTO gruppiert nach Medium",async()=>{const result=await getProjectEvidenceWithDataSource(source(),PROJECT);if(!result.success)throw new Error("read failed");expect(Object.keys(result.data.bindings[0]).sort()).toEqual(["binding_status","created_at","evidence_id","project_id","project_media_id","purpose","source_actor_class","source_channel","target"].sort());expect(JSON.stringify(result)).not.toMatch(/storage|signed|email|phone|filename/);});
 it("hält Client und Read-Grenze frei von Storage-, Admin- und Netzwerk-Capabilities",()=>{const code=["app/(app)/projects/[id]/project-media-evidence-binding.tsx","lib/actions/project-evidence-read.ts","lib/actions/project-evidence-read-service.ts"].map((p)=>readFileSync(p,"utf8")).join("\n");expect(code).not.toMatch(/SUPABASE_SERVICE_ROLE|service_role|auth\.admin|storage\.from|createSignedUrls?|\.upload\(|\.remove\(|fetch\(/i);});
});
