import {describe,expect,it} from "vitest";
import {ANSWER_INTERPRETATION_REGISTRY,QUESTION_TEMPLATE_REGISTRY,applyInformationCollectionOutcome,createSyntheticInterpretationContext,deriveMissingInformation,informationCollectionStateSchema,interpretNormalizedAnswer} from "@/lib/domain/conversation-intelligence";
const run=(key:Parameters<typeof createSyntheticInterpretationContext>[0],outcome:Parameters<typeof createSyntheticInterpretationContext>[1],text?:string)=>{const ctx=createSyntheticInterpretationContext(key,outcome);return interpretNormalizedAnswer(text?{...ctx,normalized_answer:{...ctx.normalized_answer,outcome:"answered",value:{kind:"text",value:text}}}:ctx)};
describe("AP-15-04-01-04 semantic information contracts",()=>{
 it("assigns a semantic mode to every customer question and complete meanings to booleans",()=>{expect(QUESTION_TEMPLATE_REGISTRY.filter(t=>t.customer_visible&&["question","confirmation"].includes(t.message_kind)).every(t=>t.semantic_mode)).toBe(true);expect(ANSWER_INTERPRETATION_REGISTRY.filter(r=>r.supported_normalized_kind==="boolean").every(r=>r.meanings&&Object.keys(r.meanings).sort().join(",")==="no,skip,unknown,yes")).toBe(true);});
 it.each([["outdoorPosition","false","customer_does_not_know"],["outdoorPosition","unknown","leave_information_open"],["outdoorPosition","true","customer_knows"],["indoorPosition","false","customer_does_not_know"],["lineRoute","false","requires_additional_evidence"],["electrical","false","customer_does_not_know"]] as const)("keeps %s/%s out of technical knowledge",(key,outcome,meaning)=>{const result=run(key,outcome);expect(result).toMatchObject({success:true,proposal:{claim_proposals:[],proposed_state_version:1,collection_outcome:{answer_meaning:meaning}}});if(result.success){const ctx=createSyntheticInterpretationContext(key,outcome);expect(deriveMissingInformation(ctx.knowledge_state).some(i=>i.information_key===ctx.selected_action.information_key)).toBe(true);}});
 it("treats accessibility yes/no as reported technical reachability",()=>{expect(run("accessibility","true")).toMatchObject({success:true,proposal:{claim_proposals:[{value:true}]}});expect(run("accessibility","false")).toMatchObject({success:true,proposal:{claim_proposals:[{value:false}]}});});
 it("maps controlled room and building types and fails closed",()=>{expect(run("roomType","text","Wohnzimmer")).toMatchObject({success:true,proposal:{claim_proposals:[{value:"living_room",value_type:"string"}]}});expect(run("buildingType","text","Einfamilienhaus")).toMatchObject({success:true,proposal:{claim_proposals:[{value:"single_family_house"}]}});expect(run("buildingType","text","Schloss")).toMatchObject({success:false,code:"unsupported_text_mapping",requires_human_review:false});});
 it("applies collection outcomes immutably",()=>{const ctx=createSyntheticInterpretationContext("outdoorPosition","false"),state=informationCollectionStateSchema.parse({project_id:ctx.project_id,conversation_id:ctx.conversation_id,version:0,items:[],updated_at:ctx.interpreted_at}),before=structuredClone(state);const result=applyInformationCollectionOutcome(state,{information_key:"outdoor_unit_position_known",entity_type:"installation",entity_id:ctx.selected_action.entity_id,answer_meaning:"customer_does_not_know",attempts:0},ctx.interpreted_at);expect(result.success&&result.state.items[0]).toMatchObject({collection_status:"customer_does_not_know",revisit_status:"allowed"});expect(state).toEqual(before);});
});
