import { Card, EmptyState, ErrorBox, LinkButton, SuccessBox, Badge } from "@/components/ui";
import { createClient } from "@/lib/supabase/server";
import { getCurrentUser } from "@/lib/actions/auth";
import { canCreateProject } from "@/lib/domain/permissions";
import { projectClasses, projectStatuses, type ProjectClass, type ProjectStatus } from "@/lib/domain/types";
import { statusToLabel } from "@/lib/domain/mappers";

type ProjectListRow = { id: string; title: string; status: ProjectStatus; project_class: ProjectClass | null; requires_human_review: boolean; customers: { first_name: string; last_name: string } | null };

export default async function Projects({ searchParams }: { searchParams: Promise<{ q?: string; status?: string; class?: string; review?: string; message?: string; error?: string }> }) {
  const sp = await searchParams; const supabase = await createClient(); const currentUser = await getCurrentUser();
  let query = supabase.from("projects").select("id,title,status,project_class,requires_human_review,customers(first_name,last_name)").is("deleted_at", null).order("updated_at", { ascending: false });
  if (sp.status) query = query.eq("status", sp.status); if (sp.class) query = query.eq("project_class", sp.class); if (sp.review === "true") query = query.eq("requires_human_review", true);
  const { data, error } = await query; const allProjects = (data ?? []) as ProjectListRow[]; const search = sp.q?.trim().toLowerCase(); const projects = search ? allProjects.filter((project) => `${project.title} ${project.customers?.first_name ?? ""} ${project.customers?.last_name ?? ""}`.toLowerCase().includes(search)) : allProjects;
  return <div className="space-y-6"><div className="flex flex-wrap items-center justify-between gap-3"><h1 className="text-3xl font-bold">Projektverwaltung</h1>{currentUser && canCreateProject(currentUser.role) ? <LinkButton href="/projects/new">Projekt anlegen</LinkButton> : null}</div><SuccessBox message={sp.message} /><ErrorBox message={sp.error} /><Card><form className="mb-4 grid gap-2 md:grid-cols-5"><input name="q" placeholder="Titel oder Kundenname" defaultValue={sp.q ?? ""} className="rounded border p-2 md:col-span-2"/><select name="status" defaultValue={sp.status ?? ""} className="rounded border p-2"><option value="">Alle Status</option>{projectStatuses.map((status) => <option key={status} value={status}>{statusToLabel(status)}</option>)}</select><select name="class" defaultValue={sp.class ?? ""} className="rounded border p-2"><option value="">Alle Klassen</option>{projectClasses.map((projectClass) => <option key={projectClass} value={projectClass}>{projectClass}</option>)}</select><label className="flex items-center gap-2 rounded border p-2"><input type="checkbox" name="review" value="true" defaultChecked={sp.review === "true"}/> Human Review</label><button className="rounded border px-4 py-2 md:col-span-5">Filter anwenden</button></form>{error ? <ErrorBox message="Projekte konnten nicht geladen werden." /> : projects.length === 0 ? <EmptyState>Keine aktiven Projekte gefunden.</EmptyState> : <div className="grid gap-2">{projects.map((project) => <a className="rounded border p-3 hover:bg-slate-50" href={`/projects/${project.id}`} key={project.id}><div className="flex flex-wrap items-center justify-between gap-2"><strong>{project.title}</strong><div className="flex gap-2"><Badge tone={project.requires_human_review ? "warn" : "default"}>{statusToLabel(project.status)}</Badge><Badge>{project.project_class ?? "Keine Klasse"}</Badge></div></div><p className="text-sm text-slate-600">{project.customers ? `${project.customers.first_name} ${project.customers.last_name}` : "Kein Kunde"}</p></a>)}</div>}</Card></div>;
}
