import type { RawCustomerAnswer } from "./answer-normalization-types";
import { SYNTHETIC_TEMPLATE_RENDER_FIXTURES } from "./question-template-fixtures";
import { renderQuestionTemplate } from "./question-template-renderer";

const action = SYNTHETIC_TEMPLATE_RENDER_FIXTURES.roomArea[0];
export const SYNTHETIC_ANSWER_IDS = { answer: "82000000-0000-4000-8000-000000000001", project: action.project_id, conversation: action.conversation_id, decision: action.decision_id } as const;
export const syntheticRawAnswer = (template_key: string, raw_value: RawCustomerAnswer["raw_value"], overrides: Partial<RawCustomerAnswer> = {}): RawCustomerAnswer => ({ answer_id: SYNTHETIC_ANSWER_IDS.answer, project_id: SYNTHETIC_ANSWER_IDS.project, conversation_id: SYNTHETIC_ANSWER_IDS.conversation, decision_id: SYNTHETIC_ANSWER_IDS.decision, template_key, template_version: 1, locale: "de", submitted_at: "2026-08-06T11:00:00.000Z", raw_value, ...overrides });
export const syntheticInteraction = (key: keyof typeof SYNTHETIC_TEMPLATE_RENDER_FIXTURES) => {
  const [selected_action, render_parameters] = SYNTHETIC_TEMPLATE_RENDER_FIXTURES[key];
  const result = renderQuestionTemplate({ selected_action, locale: "de", template_version: 1, render_parameters });
  if (!result.success) throw new Error("synthetic_interaction_invalid");
  return result.interaction;
};
export const SYNTHETIC_RAW_ANSWER_FIXTURES = {
  text: syntheticRawAnswer("ask_room_type", { kind: "text", value: "Wohnzimmer" }), whitespace: syntheticRawAnswer("ask_room_type", { kind: "text", value: "  Wohnzimmer \r\n oben  " }), unknownOption: syntheticRawAnswer("ask_room_type", { kind: "option", option_key: "unknown" }), unknownText: syntheticRawAnswer("ask_room_type", { kind: "text", value: "Weiß ich nicht." }), skipOption: syntheticRawAnswer("ask_room_type", { kind: "option", option_key: "skip" }), yesOption: syntheticRawAnswer("ask_indoor_position_known", { kind: "option", option_key: "yes" }), noText: syntheticRawAnswer("ask_indoor_position_known", { kind: "text", value: "Nein" }), ambiguous: syntheticRawAnswer("ask_indoor_position_known", { kind: "text", value: "vielleicht" }), exact: syntheticRawAnswer("ask_room_area_approximate", { kind: "text", value: "25" }), approximate: syntheticRawAnswer("ask_room_area_approximate", { kind: "text", value: "ca. 25 m²" }), range: syntheticRawAnswer("ask_room_area_approximate", { kind: "text", value: "20–30 qm" }), decimal: syntheticRawAnswer("ask_room_area_approximate", { kind: "text", value: "25,5" }), negative: syntheticRawAnswer("ask_room_area_approximate", { kind: "text", value: "-25" }), wrongUnit: syntheticRawAnswer("ask_room_area_approximate", { kind: "text", value: "25 Meter" }), tooHigh: syntheticRawAnswer("ask_room_area_approximate", { kind: "text", value: "9999" }), confirm: syntheticRawAnswer("confirm_room_area_assumption", { kind: "option", option_key: "confirm_assumption" }), reject: syntheticRawAnswer("confirm_room_area_assumption", { kind: "option", option_key: "reject_assumption" }), defer: syntheticRawAnswer("confirm_room_area_assumption", { kind: "option", option_key: "defer" }), stale: syntheticRawAnswer("ask_room_type", { kind: "text", value: "Wohnzimmer" }, { template_version: 2 }), wrongProject: syntheticRawAnswer("ask_room_type", { kind: "text", value: "Wohnzimmer" }, { project_id: "82000000-0000-4000-8000-000000000099" }),
} as const;
