import type { RenderedCustomerInteraction } from "./question-template-types";

export const ANSWER_NORMALIZATION_ERROR_CODES = ["invalid_raw_answer", "project_mismatch", "conversation_mismatch", "decision_mismatch", "template_key_mismatch", "template_version_mismatch", "locale_mismatch", "answer_contract_missing", "answer_contract_mismatch", "stale_answer_contract", "unsupported_answer_type", "unsupported_input_kind", "empty_answer", "answer_too_short", "answer_too_long", "unknown_not_allowed", "skip_not_allowed", "option_not_allowed", "ambiguous_boolean", "invalid_boolean", "invalid_number", "invalid_number_range", "numeric_value_too_low", "numeric_value_too_high", "numeric_range_too_wide", "unit_mismatch", "precision_not_allowed", "maximum_attempts_reached", "normalization_failed"] as const;
export type AnswerNormalizationErrorCode = typeof ANSWER_NORMALIZATION_ERROR_CODES[number];
export type RawCustomerAnswer = Readonly<{ answer_id: string; project_id: string; conversation_id: string; decision_id: string; template_key: string; template_version: number; locale: "de"; submitted_at: string; raw_value: Readonly<{ kind: "text"; value: string }> | Readonly<{ kind: "option"; option_key: string }> }>;
type AnswerBase = Readonly<Omit<RawCustomerAnswer, "raw_value">>;
export type NormalizedAnswerValue = Readonly<{ kind: "text"; value: string }> | Readonly<{ kind: "boolean"; value: boolean }> | Readonly<{ kind: "number"; approximation: "exact" | "approximate"; value: number; unit: "sqm" }> | Readonly<{ kind: "number_range"; approximation: "range"; min_value: number; max_value: number; unit: "sqm" }>;
export type NormalizedCustomerAnswer = (AnswerBase & Readonly<{ outcome: "answered"; value: NormalizedAnswerValue }>) | (AnswerBase & Readonly<{ outcome: "unknown" | "skipped" | "assumption_confirmed" | "assumption_rejected" | "deferred" | "invalid" }>);
export type AnswerNormalizationResult = Readonly<{ success: true; normalized_answer: NormalizedCustomerAnswer }> | Readonly<{ success: false; code: AnswerNormalizationErrorCode; retryable: boolean }>;
export type NormalizeCustomerAnswerInput = Readonly<{ raw_answer: RawCustomerAnswer; rendered_interaction: RenderedCustomerInteraction; attempt_number: number }>;
