import { createInterpretationIdempotencyKey } from "./answer-interpretation";
import type { InterpretationContext } from "./answer-interpretation-types";
import { selectedNextActionSchema } from "./question-planner-schemas";
import { renderQuestionTemplate } from "./question-template-renderer";
import { knowledgeStateSchema, type KnowledgeClaim } from "./schemas";
import { SYNTHETIC_TEMPLATE_RENDER_FIXTURES } from "./question-template-fixtures";

const AT = "2026-08-06T16:00:00.000Z";
const IDS = { interpretation: "83000000-0000-4000-8000-000000000001", message: "83000000-0000-4000-8000-000000000002", transition: "83000000-0000-4000-8000-000000000003", claim: "83000000-0000-4000-8000-000000000004", customerEvidence: "83000000-0000-4000-8000-000000000005", systemEvidence: "83000000-0000-4000-8000-000000000006", existingClaim: "83000000-0000-4000-8000-000000000007", existingEvidence: "83000000-0000-4000-8000-000000000008", existingSource: "83000000-0000-4000-8000-000000000009" } as const;
type FixtureKey = "roomArea" | "roomType" | "buildingType" | "indoorPosition" | "outdoorPosition" | "lineRoute" | "electrical" | "accessibility" | "assumption";
const entityType = (key: FixtureKey) => key === "buildingType" ? "project" as const : ["outdoorPosition","lineRoute","electrical","accessibility"].includes(key) ? "installation" as const : "room" as const;
export function createSyntheticInterpretationContext(key: FixtureKey = "roomArea", outcome: "exact" | "approximate" | "range" | "true" | "false" | "text" | "unknown" | "skipped" | "assumption_confirmed" | "assumption_rejected" | "deferred" = "exact", existing?: Pick<KnowledgeClaim, "value" | "value_type" | "epistemic_status"> & Partial<KnowledgeClaim>, correction_context?: InterpretationContext["correction_context"]): InterpretationContext {
  const fixture = SYNTHETIC_TEMPLATE_RENDER_FIXTURES[key]; const sourceAction = fixture[0]; const type = entityType(key);
  const action = selectedNextActionSchema.parse({ ...sourceAction, entity_type: type, entity_id: type === "project" ? sourceAction.project_id : type === "installation" ? "81000000-0000-4000-8000-000000000006" : sourceAction.entity_id });
  const rendered = renderQuestionTemplate({ selected_action: action, locale: "de", template_version: 1, render_parameters: fixture[1] }); if (!rendered.success) throw new Error("fixture_render_failed");
  const binding = { answer_id: "82000000-0000-4000-8000-000000000001", project_id: action.project_id, conversation_id: action.conversation_id, decision_id: action.decision_id, template_key: rendered.interaction.template_key, template_version: 1, locale: "de" as const, submitted_at: AT };
  const normalized_answer = outcome === "exact" ? { ...binding, outcome: "answered" as const, value: { kind: "number" as const, approximation: "exact" as const, value: 25, unit: "sqm" as const } } : outcome === "approximate" ? { ...binding, outcome: "answered" as const, value: { kind: "number" as const, approximation: "approximate" as const, value: 25, unit: "sqm" as const } } : outcome === "range" ? { ...binding, outcome: "answered" as const, value: { kind: "number_range" as const, approximation: "range" as const, min_value: 20, max_value: 30, unit: "sqm" as const } } : outcome === "true" || outcome === "false" ? { ...binding, outcome: "answered" as const, value: { kind: "boolean" as const, value: outcome === "true" } } : outcome === "text" ? { ...binding, outcome: "answered" as const, value: { kind: "text" as const, value: "synthetischer Text" } } : { ...binding, outcome };
  const claims: KnowledgeClaim[] = existing ? [{ ...existing, claim_id: IDS.existingClaim, project_id: action.project_id, entity_type: type, entity_id: action.entity_id, property_key: action.information_key, value: existing.value, value_type: existing.value_type, epistemic_status: existing.epistemic_status, evidence: existing.evidence ?? [{ evidence_id: IDS.existingEvidence, source_type: "customer_message", source_id: IDS.existingSource, actor_class: "customer", observed_at: AT, evidence_status: "active" }], created_at: AT, state_version: 1 }] as KnowledgeClaim[] : [];
  const knowledge_state = knowledgeStateSchema.parse({ project_id: action.project_id, conversation_id: action.conversation_id, state_version: 1, claims, updated_at: AT });
  return { interpretation_id: IDS.interpretation, project_id: action.project_id, conversation_id: action.conversation_id, current_state_version: 1, knowledge_state, selected_action: action, rendered_interaction: rendered.interaction, normalized_answer, source_message_id: IDS.message, source_actor_class: "customer", interpreted_at: AT, idempotency_key: createInterpretationIdempotencyKey(action.conversation_id, action.decision_id, binding.answer_id), ...(correction_context ? { correction_context } : {}), proposal_ids: { transition_id: IDS.transition, claim_id: IDS.claim, customer_evidence_id: IDS.customerEvidence, system_evidence_id: IDS.systemEvidence } };
}
export const SYNTHETIC_INTERPRETATION_FIXTURES = Object.freeze({
  A: createSyntheticInterpretationContext("roomArea", "exact"), B: createSyntheticInterpretationContext("roomArea", "approximate"), C: createSyntheticInterpretationContext("roomArea", "range"), D: createSyntheticInterpretationContext("indoorPosition", "true"), E: createSyntheticInterpretationContext("outdoorPosition", "false"), F: createSyntheticInterpretationContext("roomType", "text"), G: createSyntheticInterpretationContext("roomArea", "unknown"), H: createSyntheticInterpretationContext("buildingType", "skipped"), I: createSyntheticInterpretationContext("assumption", "assumption_confirmed"), J: createSyntheticInterpretationContext("assumption", "assumption_rejected"), K: createSyntheticInterpretationContext("assumption", "deferred"),
  L: createSyntheticInterpretationContext("roomArea", "exact", { value: null, value_type: "unknown", epistemic_status: "unknown" }),
  M: createSyntheticInterpretationContext("roomArea", "exact", { value: 20, value_type: "number", epistemic_status: "assumed" }),
  N: createSyntheticInterpretationContext("roomArea", "exact", { value: 25, value_type: "number", epistemic_status: "reported" }),
  O: createSyntheticInterpretationContext("roomArea", "exact", { value: 30, value_type: "number", epistemic_status: "reported" }),
  P: createSyntheticInterpretationContext("roomArea", "exact", { value: 30, value_type: "number", epistemic_status: "reported" }, "explicit_customer_correction"),
  Q: createSyntheticInterpretationContext("roomArea", "exact", { value: 30, value_type: "number", epistemic_status: "confirmed", evidence: [{ evidence_id: IDS.existingEvidence, source_type: "reviewer_correction", source_id: IDS.existingSource, actor_class: "reviewer", observed_at: AT, evidence_status: "manually_corrected" }] }),
  R: { ...createSyntheticInterpretationContext(), current_state_version: 2 },
  S: { ...createSyntheticInterpretationContext(), selected_action: { ...createSyntheticInterpretationContext().selected_action, entity_type: "installation" } },
  T: { ...createSyntheticInterpretationContext(), selected_action: { ...createSyntheticInterpretationContext().selected_action, information_key: "desired_installation_scope", entity_type: "project" } },
});
