import { z } from "zod";
import { normalizedCustomerAnswerSchema } from "./answer-normalization-schemas";
import { selectedNextActionSchema } from "./question-planner-schemas";
import { renderedCustomerInteractionSchema } from "./question-template-schemas";
import { knowledgeStateSchema } from "./schemas";
import { ALL_PROPERTY_KEYS, ENTITY_TYPES, EPISTEMIC_STATUSES } from "./types";
import { ANSWER_MEANINGS, QUESTION_SEMANTIC_MODES } from "./information-collection";
import { EXPLANATION_CODES, INTERPRETATION_ERROR_CODES, SUPERSESSION_REASON_CODES, TRANSITION_TYPES } from "./answer-interpretation-types";

const uuid = z.string().uuid(); const timestamp = z.string().datetime({ offset: true }); const version = z.number().int().positive();
export const approximationSchema = z.enum(["exact", "approximate"]);
export const mappingRuleSchema = z.object({ information_key: z.enum(ALL_PROPERTY_KEYS), entity_type: z.enum(ENTITY_TYPES), property_key: z.enum(ALL_PROPERTY_KEYS), supported_normalized_kind: z.enum(["number", "boolean", "text"]), epistemic_status: z.literal("reported"), unknown_strategy: z.literal("null_claim"), skip_strategy: z.literal("no_property_claim"), contradiction_strategy: z.literal("parallel_claim"), supersession_strategy: z.literal("controlled"), evidence_source_type: z.literal("customer_message"), supports_assumption: z.boolean(), status: z.enum(["active", "deferred"]), semantic_mode:z.enum(QUESTION_SEMANTIC_MODES), meanings:z.object({yes:z.enum(ANSWER_MEANINGS),no:z.enum(ANSWER_MEANINGS),unknown:z.enum(ANSWER_MEANINGS),skip:z.enum(ANSWER_MEANINGS)}).strict().optional(), canonical_values:z.record(z.string(),z.string()).optional() }).strict();
export const evidenceProposalSchema = z.object({ evidence_id: uuid, source_type: z.enum(["customer_message", "system_rule"]), source_id: uuid, actor_class: z.enum(["customer", "system"]), observed_at: timestamp, evidence_status: z.literal("active") }).strict();
export const knowledgeClaimProposalSchema = z.object({ claim_id: uuid, project_id: uuid, entity_type: z.enum(ENTITY_TYPES), entity_id: uuid, property_key: z.enum(ALL_PROPERTY_KEYS), value: z.union([z.string().min(1), z.number().finite(), z.boolean(), z.null()]), value_type: z.enum(["string", "number", "boolean", "unknown"]), epistemic_status: z.enum(EPISTEMIC_STATUSES), evidence: z.array(evidenceProposalSchema).min(1).readonly(), based_on_state_version: version, proposed_state_version: version, supersedes_claim_id: uuid.optional(), approximation: approximationSchema.optional(), proposal_reason_codes: z.array(z.enum(SUPERSESSION_REASON_CODES)).readonly() }).strict().superRefine((claim, context) => {
  if (claim.proposed_state_version !== claim.based_on_state_version + 1) context.addIssue({ code: "custom", message: "proposal_version_mismatch" });
  if ((claim.value_type === "unknown") !== (claim.value === null && claim.epistemic_status === "unknown")) context.addIssue({ code: "custom", message: "unknown_value_mismatch" });
  if ((claim.value_type === "string") !== (typeof claim.value === "string")) context.addIssue({ code: "custom", message: "string_value_mismatch" });
  if ((claim.value_type === "number") !== (typeof claim.value === "number")) context.addIssue({ code: "custom", message: "number_value_mismatch" });
  if ((claim.value_type === "boolean") !== (typeof claim.value === "boolean")) context.addIssue({ code: "custom", message: "boolean_value_mismatch" });
  if (claim.approximation && claim.value_type !== "number") context.addIssue({ code: "custom", message: "approximation_value_mismatch" });
});
export const interpretationContextSchema = z.object({ interpretation_id: uuid, project_id: uuid, conversation_id: uuid, current_state_version: version, knowledge_state: knowledgeStateSchema, selected_action: selectedNextActionSchema, rendered_interaction: renderedCustomerInteractionSchema, normalized_answer: normalizedCustomerAnswerSchema, source_message_id: uuid, source_actor_class: z.literal("customer"), interpreted_at: timestamp, idempotency_key: z.string().min(1), correction_context: z.enum(["none", "explicit_customer_correction"]).optional(), proposal_ids: z.object({ transition_id: uuid, claim_id: uuid, customer_evidence_id: uuid, system_evidence_id: uuid.optional() }).strict(), application_status: z.enum(["not_applied", "duplicate_answer", "mapping_already_applied"]).optional() }).strict();
const transitionBase = { transition_id: uuid, interpretation_id: uuid, idempotency_key: z.string().min(1), project_id: uuid, conversation_id: uuid, based_on_state_version: version, proposed_state_version: version, answer_id: uuid, information_key: z.enum(ALL_PROPERTY_KEYS), evidence_proposals: z.array(evidenceProposalSchema).readonly(), claim_proposals: z.array(knowledgeClaimProposalSchema).readonly(), superseded_claim_ids: z.array(uuid).readonly(), retry_outcome: z.enum(["answered", "unknown", "skipped"]), explanation_codes: z.array(z.enum(EXPLANATION_CODES)).readonly(), created_at: timestamp, semantic_result_type:z.enum(["technical_transition","collection_update_only","technical_and_collection_update","no_change","unsupported_mapping"]), collection_outcome:z.object({information_key:z.enum(ALL_PROPERTY_KEYS),entity_type:z.enum(ENTITY_TYPES),entity_id:uuid,answer_meaning:z.enum(ANSWER_MEANINGS),attempts:z.number().int().min(0).max(2)}).strict().optional() };
export const stateTransitionProposalSchema = z.discriminatedUnion("transition_type", TRANSITION_TYPES.map((transition_type) => z.object({ ...transitionBase, transition_type: z.literal(transition_type) }).strict()) as unknown as [z.ZodDiscriminatedUnionOption<"transition_type">, ...z.ZodDiscriminatedUnionOption<"transition_type">[]]).superRefine((proposal, context) => {
  const noChange = proposal.claim_proposals.length === 0 || ["skip_recorded", "assumption_rejected", "assumption_deferred", "duplicate_no_change", "human_review_required"].includes(proposal.transition_type as string);
  if (proposal.proposed_state_version !== proposal.based_on_state_version + (noChange ? 0 : 1)) context.addIssue({ code: "custom", message: "transition_version_mismatch" });
});
export const interpretationResultSchema = z.discriminatedUnion("success", [z.object({ success: z.literal(true), proposal: stateTransitionProposalSchema, code: z.literal("idempotent_success").optional() }).strict(), z.object({ success: z.literal(false), code: z.enum(INTERPRETATION_ERROR_CODES), retryable: z.boolean(), requires_replanning: z.boolean(), requires_human_review: z.boolean(), causes_state_change: z.literal(false) }).strict()]);
