import type { NormalizedCustomerAnswer } from "./answer-normalization-types";
import type { SelectedNextAction } from "./question-planner-schemas";
import type { RenderedCustomerInteraction } from "./question-template-types";
import type { KnowledgeState } from "./schemas";
import type { EntityType, EpistemicStatus, PropertyKey } from "./types";
import type { AnswerMeaning, InformationCollectionOutcome } from "./information-collection";

export const INTERPRETATION_ERROR_CODES = ["invalid_interpretation_context", "project_mismatch", "conversation_mismatch", "state_version_mismatch", "decision_mismatch", "template_binding_mismatch", "answer_binding_mismatch", "mapping_rule_not_found", "information_property_mismatch", "entity_type_mismatch", "entity_id_mismatch", "entity_not_found", "answer_value_type_mismatch", "unsupported_answer_outcome", "unsupported_text_mapping", "numeric_range_not_supported", "assumption_key_missing", "assumption_not_allowed", "evidence_binding_invalid", "duplicate_answer", "mapping_already_applied", "contradiction_requires_review", "supersession_not_allowed", "reviewer_correction_protected", "human_review_required", "interpretation_failed"] as const;
export const INTERPRETATION_RESULT_CODES = ["duplicate_answer", "mapping_already_applied", "idempotent_success"] as const;
export const TRANSITION_TYPES = ["claim_created", "claim_supersession_proposed", "unknown_recorded", "skip_recorded", "assumption_confirmed", "assumption_rejected", "assumption_deferred", "duplicate_no_change", "contradiction_recorded", "human_review_required"] as const;
export const EXPLANATION_CODES = ["mapping_rule_applied", "customer_answer_reported", "approximate_value_preserved", "unknown_value_recorded", "skip_without_property_claim", "assumption_value_from_server_rule", "customer_confirmation_evidence_added", "existing_unknown_superseded", "existing_assumption_superseded", "duplicate_value_detected", "contradiction_preserved", "explicit_correction_applied", "reviewer_claim_protected", "numeric_range_deferred"] as const;
export const SUPERSESSION_REASON_CODES = ["unknown_replaced_by_reported_value", "assumption_replaced_by_reported_value", "explicit_customer_correction", "duplicate_value_no_change", "parallel_contradictory_claim", "reviewer_correction_protected", "supersession_not_allowed"] as const;

export type InterpretationErrorCode = typeof INTERPRETATION_ERROR_CODES[number];
export type ExplanationCode = typeof EXPLANATION_CODES[number];
export type SupersessionReasonCode = typeof SUPERSESSION_REASON_CODES[number];
export type MappingRule = Readonly<{ information_key: PropertyKey; entity_type: EntityType; property_key: PropertyKey; supported_normalized_kind: "number" | "boolean" | "text"; epistemic_status: "reported"; unknown_strategy: "null_claim"; skip_strategy: "no_property_claim"; contradiction_strategy: "parallel_claim"; supersession_strategy: "controlled"; evidence_source_type: "customer_message"; supports_assumption: boolean; status: "active" | "deferred"; semantic_mode: "technical_property" | "customer_knowledge" | "customer_preference" | "customer_observation" | "collection_capability"; meanings?: Readonly<{ yes: AnswerMeaning; no: AnswerMeaning; unknown: AnswerMeaning; skip: AnswerMeaning }>; canonical_values?: Readonly<Record<string, string>> }>;
export type EvidenceProposal = Readonly<{ evidence_id: string; source_type: "customer_message" | "system_rule"; source_id: string; actor_class: "customer" | "system"; observed_at: string; evidence_status: "active" }>;
export type KnowledgeClaimProposal = Readonly<{ claim_id: string; project_id: string; entity_type: EntityType; entity_id: string; property_key: PropertyKey; value: string | number | boolean | null; value_type: "string" | "number" | "boolean" | "unknown"; epistemic_status: EpistemicStatus; evidence: readonly EvidenceProposal[]; based_on_state_version: number; proposed_state_version: number; supersedes_claim_id?: string; approximation?: "exact" | "approximate"; proposal_reason_codes: readonly SupersessionReasonCode[] }>;
export type ProposalIds = Readonly<{ transition_id: string; claim_id: string; customer_evidence_id: string; system_evidence_id?: string }>;
export type InterpretationContext = Readonly<{ interpretation_id: string; project_id: string; conversation_id: string; current_state_version: number; knowledge_state: KnowledgeState; selected_action: SelectedNextAction; rendered_interaction: RenderedCustomerInteraction; normalized_answer: NormalizedCustomerAnswer; source_message_id: string; source_actor_class: "customer"; interpreted_at: string; idempotency_key: string; correction_context?: "none" | "explicit_customer_correction"; proposal_ids: ProposalIds; application_status?: "not_applied" | "duplicate_answer" | "mapping_already_applied" }>;
type TransitionBase = Readonly<{ transition_id: string; interpretation_id: string; idempotency_key: string; project_id: string; conversation_id: string; based_on_state_version: number; proposed_state_version: number; answer_id: string; information_key: PropertyKey; evidence_proposals: readonly EvidenceProposal[]; claim_proposals: readonly KnowledgeClaimProposal[]; superseded_claim_ids: readonly string[]; retry_outcome: "answered" | "unknown" | "skipped"; explanation_codes: readonly ExplanationCode[]; created_at: string; semantic_result_type: "technical_transition" | "collection_update_only" | "technical_and_collection_update" | "no_change" | "unsupported_mapping"; collection_outcome?: InformationCollectionOutcome }>;
export type StateTransitionProposal = { [Kind in typeof TRANSITION_TYPES[number]]: TransitionBase & Readonly<{ transition_type: Kind }> }[typeof TRANSITION_TYPES[number]];
export type InterpretationResult = Readonly<{ success: true; proposal: StateTransitionProposal; code?: "idempotent_success" }> | Readonly<{ success: false; code: InterpretationErrorCode; retryable: boolean; requires_replanning: boolean; requires_human_review: boolean; causes_state_change: false }>;
