import { applyInformationCollectionOutcome } from "./information-collection";
import { interpretNormalizedAnswer } from "./answer-interpretation";
import { conversationCycleContextSchema } from "./conversation-cycle-schemas";
import type { ConversationCycleContext, ConversationCycleFailure, ConversationCycleResult, CycleErrorCode } from "./conversation-cycle-types";
import { deriveConversationEvents } from "./conversation-events";
import { applyCustomerEffortOutcome, applyRetryOutcome } from "./conversation-retry-state";
import { buildIntermediateAssessment } from "./intermediate-assessment";
import { generateQuestionCandidates, planNextAction } from "./question-planner";
import type { PlanNextActionResult, SelectedNextAction } from "./question-planner-schemas";
import { renderQuestionTemplate } from "./question-template-renderer";
import type { RenderParameters } from "./question-template-types";
import { deriveMissingInformation, deriveReadiness } from "./readiness";
import { applyStateTransitionProposal } from "./state-transition";
import type { IntermediateAssessment } from "./schemas";
import { appendPlannedEvidenceRequest, planEvidenceRequest } from "./evidence-request";
import { derivePlannerEvidenceContext } from "./planner-evidence-context";
import { getEffectiveClaims } from "./knowledge-state";
import type { PropertyKey } from "./types";

const FLAGS:Record<CycleErrorCode,[boolean,boolean,boolean]>={invalid_cycle_context:[false,false,false],cycle_state_version_mismatch:[false,true,false],interpretation_failed:[false,false,false],transition_application_failed:[false,false,false],retry_state_application_failed:[false,false,false],collection_state_application_failed:[false,false,false],customer_effort_application_failed:[false,false,false],event_derivation_failed:[false,false,false],missing_information_derivation_failed:[false,false,false],readiness_derivation_failed:[false,false,false],assessment_creation_failed:[false,false,false],planner_failed:[false,true,false],template_render_failed:[false,true,false],cycle_version_invariant_failed:[false,true,true],cycle_already_processed:[false,false,false],human_review_required:[false,false,true],conversation_cycle_failed:[true,false,true]};
const failure=(code:CycleErrorCode):ConversationCycleFailure=>{const [retryable,requires_replanning,requires_human_review]=FLAGS[code];return{success:false,code,retryable,requires_replanning,requires_human_review}};
function intermediateParameters(assessment:IntermediateAssessment):RenderParameters{return{assessment_level_label:assessment.readiness_level,known_items:[...assessment.known_facts,...assessment.reported_information],assumption_items:assessment.assumptions,open_items:assessment.unknowns,next_step_label:"offene Informationen klären"};}
function render(action:SelectedNextAction,ctx:ConversationCycleContext,assessment:Parameters<typeof intermediateParameters>[0]){if(!action.template_key||action.action_type==="request_human_review")return undefined;const params=action.action_type==="present_intermediate_result"?intermediateParameters(assessment):action.action_type==="offer_assumption"?{approximate_example:"25 m²"}:{};return renderQuestionTemplate({selected_action:action,locale:ctx.locale,template_version:ctx.template_version,render_parameters:params});}
export function runConversationCycle(input:unknown):ConversationCycleResult{
 const parsed=conversationCycleContextSchema.safeParse(input);if(!parsed.success)return failure("invalid_cycle_context");const ctx=parsed.data as ConversationCycleContext;
 if(ctx.execution_status==="already_processed")return failure("cycle_already_processed");
 if(ctx.expected_state_version!==ctx.knowledge_state.state_version||ctx.interpretation_inputs.selected_action.based_on_state_version!==ctx.expected_state_version)return failure("cycle_state_version_mismatch");
 const interpretation=interpretNormalizedAnswer({...ctx.interpretation_inputs,project_id:ctx.project_id,conversation_id:ctx.conversation_id,current_state_version:ctx.expected_state_version,knowledge_state:ctx.knowledge_state,normalized_answer:ctx.normalized_answer});
 if(!interpretation.success)return interpretation.requires_human_review?failure("human_review_required"):failure("interpretation_failed");
 const applied=applyStateTransitionProposal({project_id:ctx.project_id,conversation_id:ctx.conversation_id,current_state:ctx.knowledge_state,proposal:interpretation.proposal,applied_at:ctx.occurred_at,apply_id:ctx.next_state_ids.apply_id,idempotency_status:"not_applied"});
 if(!applied.success)return applied.requires_human_review?failure("human_review_required"):failure("transition_application_failed");
 if(applied.code==="transition_already_applied")return failure("cycle_already_processed");
 const action=ctx.interpretation_inputs.selected_action;const prior=ctx.retry_state.items.find(i=>i.information_key===action.information_key&&i.entity_type===action.entity_type&&i.entity_id===action.entity_id);
 const retry=applyRetryOutcome(ctx.retry_state,{information_key:action.information_key,entity_type:action.entity_type,entity_id:action.entity_id,retry_outcome:interpretation.proposal.retry_outcome,occurred_at:ctx.occurred_at});if(!retry.success)return failure("retry_state_application_failed");
 const effort=applyCustomerEffortOutcome(ctx.customer_effort_state,action,interpretation.proposal.retry_outcome,Boolean(prior?.attempts),ctx.occurred_at);
 const collection=interpretation.proposal.collection_outcome?applyInformationCollectionOutcome(ctx.information_collection_state,{...interpretation.proposal.collection_outcome,attempts:retry.state.items.find(i=>i.information_key===action.information_key&&i.entity_id===action.entity_id)?.attempts??interpretation.proposal.collection_outcome.attempts},ctx.occurred_at):{success:true as const,state:ctx.information_collection_state,changed:false as const,result_code:"collection_outcome_unchanged" as const};if(!collection.success)return failure("collection_state_application_failed");
 if(interpretation.proposal.transition_type==="human_review_required")return failure("human_review_required");
 const state=applied.knowledge_state,missing=deriveMissingInformation(state),readiness=deriveReadiness(state),assessment=buildIntermediateAssessment(state,{assessment_id:ctx.assessment_id,project_id:ctx.project_id,conversation_id:ctx.conversation_id,based_on_state_version:applied.new_state_version,created_at:ctx.occurred_at,created_by_actor_class:"system"});if(!assessment.success)return failure("assessment_creation_failed");
 const planned=planNextAction({project_id:ctx.project_id,conversation_id:ctx.conversation_id,state_version:applied.new_state_version,knowledge_state:state,information_collection_state:collection.state,intermediate_assessment:assessment.data,missing_information:missing,target_readiness_level:"level_3_preliminary_installation",retry_state:retry.state.items,revisit_triggers:[],customer_effort_state:effort,created_at:ctx.occurred_at},{decision_id:ctx.planner_decision_id,created_at:ctx.occurred_at});if(!planned.success)return failure("planner_failed");
 const plannerResult:PlanNextActionResult=planned.data;if(assessment.data.based_on_state_version!==applied.new_state_version||(plannerResult.kind==="selected_action"?plannerResult.action.based_on_state_version:plannerResult.stop.based_on_state_version)!==applied.new_state_version)return failure("cycle_version_invariant_failed");
 let evidenceState=ctx.evidence_request_state,selectedEvidence,renderedEvidence;
 if(plannerResult.kind==="stop_result"&&plannerResult.stop.stop_reason==="no_eligible_customer_action"){
  const candidates=generateQuestionCandidates({project_id:ctx.project_id,conversation_id:ctx.conversation_id,state_version:applied.new_state_version,knowledge_state:state,information_collection_state:collection.state,intermediate_assessment:assessment.data,missing_information:missing,target_readiness_level:"level_3_preliminary_installation",retry_state:retry.state.items,revisit_triggers:[],customer_effort_state:effort,created_at:ctx.occurred_at});
  if(!candidates.success)return failure("planner_failed");
  const needs=candidates.data.filter(candidate=>candidate.collection_path==="future_photo_request").map(candidate=>({information_key:candidate.information_key,entity_type:candidate.entity_type,entity_id:candidate.entity_id,open:true as const,collection_path:"future_photo_request" as const}));
  if(needs.length){const availableKeys=new Set<PropertyKey>();for(const claim of getEffectiveClaims(state))if(!["unknown","contradicted"].includes(claim.epistemic_status))availableKeys.add(claim.property_key);for(const item of collection.state.items)if(["answered","resolved"].includes(item.collection_status))availableKeys.add(item.information_key);
   const evidence=planEvidenceRequest({project_id:ctx.project_id,conversation_id:ctx.conversation_id,request_id:ctx.next_evidence_request_id,needs,request_state:evidenceState,availability:ctx.evidence_availability,evidence_context:derivePlannerEvidenceContext(state),available_dependency_keys:[...availableKeys],human_review_required:false,site_check_authoritative:false,consecutive_evidence_requests:evidenceState.requests.slice(-2).length,total_evidence_requests:evidenceState.requests.length});
   if(evidence.kind==="evidence_request_selected"){selectedEvidence=evidence.request;renderedEvidence=evidence.rendered;evidenceState=appendPlannedEvidenceRequest(evidenceState,evidence.request,ctx.occurred_at);}
  }
 }
 let rendered; if(plannerResult.kind==="selected_action"){const result=render(plannerResult.action,ctx,assessment.data);if(result&&!result.success)return failure("template_render_failed");rendered=result?.interaction;}
 const status=selectedEvidence?"evidence_request_selected":plannerResult.kind==="selected_action"?(plannerResult.action.action_type==="request_human_review"?"human_review_required":applied.changed?"next_action_selected":"no_state_change"):plannerResult.stop.next_action_type==="request_human_review"?"human_review_required":plannerResult.stop.next_action_type==="present_intermediate_result"?"intermediate_result_ready":"collection_stopped";
 const events=deriveConversationEvents({interpretation,proposal:interpretation.proposal,apply_result:applied,event_ids:ctx.event_ids,sequence_start:ctx.event_sequence_start,occurred_at:ctx.occurred_at,correlation_id:ctx.correlation_id,result_code:status});if(!events.success)return failure("event_derivation_failed");
 return{success:true,cycle_status:status,previous_state_version:applied.previous_state_version,current_state_version:applied.new_state_version,knowledge_state:state,information_collection_state:collection.state,retry_state:retry.state,customer_effort_state:effort,evidence_request_state:evidenceState,evidence_availability:ctx.evidence_availability,...(selectedEvidence?{selected_evidence_request:selectedEvidence,rendered_evidence_request:renderedEvidence}:{}),missing_information:missing,readiness,assessment:assessment.data,planner_result:plannerResult,...(rendered?{rendered_interaction:rendered}:{}),events:events.events};
}
