import { z } from "zod";
import { ALL_PROPERTY_KEYS, ENTITY_TYPES, type PropertyKey } from "./types";

export const EVIDENCE_REQUEST_ACTION_TYPES = ["request_photo", "request_multiple_photos", "request_document", "no_evidence_request"] as const;
export const EVIDENCE_TARGET_STATUSES = ["active", "deferred"] as const;
export const EVIDENCE_REQUEST_STATUSES = ["planned", "requested", "provided", "skipped", "declined", "superseded", "cancelled"] as const;
export const EVIDENCE_AVAILABILITY_STATUSES = ["not_requested", "requested", "available_unanalysed", "analysed", "invalid", "unusable"] as const;
export const EVIDENCE_REQUIRED_VIEWS = ["wide_overview", "straight_on", "include_surroundings", "include_floor_and_ceiling", "include_adjacent_wall", "include_distance_reference"] as const;
export const EVIDENCE_PURPOSE_CODES = ["evaluate_indoor_position_context", "evaluate_outdoor_position_context", "evaluate_line_route_context", "evaluate_room_dimension_context", "evaluate_electrical_context", "evaluate_accessibility_context", "evaluate_condensate_context", "evaluate_core_drilling_context", "evaluate_building_context"] as const;
export const EVIDENCE_TARGET_KEYS = ["indoor_area_overview", "outdoor_area_overview", "indoor_unit_wall", "outdoor_unit_location", "line_route_context", "electrical_area", "accessibility_context", "room_overview", "room_dimensions_context", "building_exterior_context", "condensate_context", "core_drilling_context"] as const;
export const EVIDENCE_BUNDLE_KEYS = ["indoor_context_bundle", "outdoor_context_bundle", "installation_route_bundle"] as const;
export const EVIDENCE_TEMPLATE_KEYS = ["evidence_room_overview", "evidence_indoor_area_overview", "evidence_outdoor_area_overview", "evidence_line_route_context", "evidence_electrical_area", "evidence_accessibility_context", "evidence_indoor_context_bundle"] as const;
export const EVIDENCE_REQUEST_REASON_CODES = ["open_information_need", "future_photo_path", "covers_multiple_needs", "controlled_bundle", "dependency_context_available"] as const;
export const NO_EVIDENCE_REQUEST_REASONS = ["collection_path_not_eligible", "no_active_target", "dependency_not_satisfied", "duplicate_request", "evidence_already_available", "request_limit_reached", "human_review_required", "site_check_authoritative", "document_request_deferred"] as const;

const uuid=z.string().uuid(), timestamp=z.string().datetime({offset:true});
export const evidenceTargetKeySchema=z.enum(EVIDENCE_TARGET_KEYS);
export const evidencePurposeCodeSchema=z.enum(EVIDENCE_PURPOSE_CODES);
export const evidenceRequestItemSchema=z.object({request_id:uuid,target_key:evidenceTargetKeySchema,bundle_key:z.enum(EVIDENCE_BUNDLE_KEYS).optional(),requested_for_information_keys:z.array(z.enum(ALL_PROPERTY_KEYS)).min(1).readonly(),purpose_codes:z.array(evidencePurposeCodeSchema).min(1).readonly(),status:z.enum(EVIDENCE_REQUEST_STATUSES),attempts:z.number().int().min(1).max(2),requested_at:timestamp,resolved_at:timestamp.optional()}).strict();
export const evidenceRequestStateSchema=z.object({project_id:uuid,conversation_id:uuid,requests:z.array(evidenceRequestItemSchema).readonly(),revision:z.number().int().nonnegative()}).strict().superRefine((state,ctx)=>{if(new Set(state.requests.map(r=>r.request_id)).size!==state.requests.length)ctx.addIssue({code:"custom",message:"duplicate_request_id"});});
export const evidenceAvailabilitySchema=z.object({target_key:evidenceTargetKeySchema,status:z.enum(EVIDENCE_AVAILABILITY_STATUSES),request_id:uuid.optional()}).strict();
export const selectedEvidenceRequestSchema=z.object({request_id:uuid,action_type:z.enum(EVIDENCE_REQUEST_ACTION_TYPES).exclude(["request_document","no_evidence_request"]),target_key:evidenceTargetKeySchema,bundle_key:z.enum(EVIDENCE_BUNDLE_KEYS).optional(),information_keys:z.array(z.enum(ALL_PROPERTY_KEYS)).min(1).readonly(),purpose_codes:z.array(evidencePurposeCodeSchema).min(1).readonly(),template_key:z.enum(EVIDENCE_TEMPLATE_KEYS),required_views:z.array(z.enum(EVIDENCE_REQUIRED_VIEWS)).min(1).readonly(),minimum_count:z.number().int().positive(),maximum_count:z.number().int().positive(),request_reason_codes:z.array(z.enum(EVIDENCE_REQUEST_REASON_CODES)).min(1).readonly()}).strict().refine(v=>v.maximum_count>=v.minimum_count,{message:"invalid_count_range"});
export type EvidenceRequestState=z.infer<typeof evidenceRequestStateSchema>;
export type EvidenceAvailability=z.infer<typeof evidenceAvailabilitySchema>;
export type SelectedEvidenceRequest=z.infer<typeof selectedEvidenceRequestSchema>;
export type EvidenceTargetKey=typeof EVIDENCE_TARGET_KEYS[number];
export type EvidencePurposeCode=typeof EVIDENCE_PURPOSE_CODES[number];

export type EvidenceTargetDefinition=Readonly<{target_key:EvidenceTargetKey;status:typeof EVIDENCE_TARGET_STATUSES[number];supports_information_keys:readonly PropertyKey[];purpose_codes:readonly EvidencePurposeCode[];required_views:readonly typeof EVIDENCE_REQUIRED_VIEWS[number][];minimum_count:number;maximum_count:number;template_key?:typeof EVIDENCE_TEMPLATE_KEYS[number];dependency_keys:readonly PropertyKey[];safety_constraints:readonly ("do_not_open_equipment"|"do_not_use_ladders"|"do_not_climb"|"do_not_move_heavy_objects"|"do_not_enter_hazardous_areas")[]}>;
const target=(definition:EvidenceTargetDefinition)=>Object.freeze({...definition,supports_information_keys:Object.freeze([...definition.supports_information_keys]),purpose_codes:Object.freeze([...definition.purpose_codes]),required_views:Object.freeze([...definition.required_views]),dependency_keys:Object.freeze([...definition.dependency_keys]),safety_constraints:Object.freeze([...definition.safety_constraints])});
const safe=["do_not_open_equipment","do_not_use_ladders","do_not_climb","do_not_move_heavy_objects","do_not_enter_hazardous_areas"] as const;
export const EVIDENCE_TARGET_REGISTRY=Object.freeze([
 target({target_key:"room_overview",status:"active",supports_information_keys:["room_area_sqm"],purpose_codes:["evaluate_room_dimension_context"],required_views:["wide_overview","include_floor_and_ceiling"],minimum_count:1,maximum_count:2,template_key:"evidence_room_overview",dependency_keys:[],safety_constraints:safe}),
 target({target_key:"indoor_area_overview",status:"active",supports_information_keys:["indoor_unit_position_known"],purpose_codes:["evaluate_indoor_position_context"],required_views:["wide_overview","include_surroundings"],minimum_count:1,maximum_count:2,template_key:"evidence_indoor_area_overview",dependency_keys:["room_type"],safety_constraints:safe}),
 target({target_key:"outdoor_area_overview",status:"active",supports_information_keys:["outdoor_unit_position_known","accessibility_known","line_route_known"],purpose_codes:["evaluate_outdoor_position_context","evaluate_accessibility_context","evaluate_line_route_context"],required_views:["wide_overview","include_surroundings"],minimum_count:1,maximum_count:2,template_key:"evidence_outdoor_area_overview",dependency_keys:["building_type"],safety_constraints:safe}),
 target({target_key:"line_route_context",status:"active",supports_information_keys:["line_route_known"],purpose_codes:["evaluate_line_route_context"],required_views:["wide_overview","include_adjacent_wall"],minimum_count:1,maximum_count:2,template_key:"evidence_line_route_context",dependency_keys:["indoor_unit_position_known","outdoor_unit_position_known"],safety_constraints:safe}),
 target({target_key:"electrical_area",status:"active",supports_information_keys:["electrical_supply_known"],purpose_codes:["evaluate_electrical_context"],required_views:["straight_on","include_surroundings"],minimum_count:1,maximum_count:1,template_key:"evidence_electrical_area",dependency_keys:[],safety_constraints:safe}),
 target({target_key:"accessibility_context",status:"active",supports_information_keys:["accessibility_known"],purpose_codes:["evaluate_accessibility_context"],required_views:["wide_overview","include_surroundings"],minimum_count:1,maximum_count:1,template_key:"evidence_accessibility_context",dependency_keys:["indoor_unit_position_known"],safety_constraints:safe}),
 ...(["indoor_unit_wall","outdoor_unit_location","room_dimensions_context","building_exterior_context","condensate_context","core_drilling_context"] as const).map(target_key=>target({target_key,status:"deferred",supports_information_keys:target_key==="indoor_unit_wall"?["indoor_unit_position_known"]:target_key==="outdoor_unit_location"?["outdoor_unit_position_known"]:target_key==="room_dimensions_context"?["room_area_sqm"]:target_key==="building_exterior_context"?["building_type"]:target_key==="condensate_context"?["condensate_route_known"]:["core_drilling_count"],purpose_codes:[target_key==="indoor_unit_wall"?"evaluate_indoor_position_context":target_key==="outdoor_unit_location"?"evaluate_outdoor_position_context":target_key==="room_dimensions_context"?"evaluate_room_dimension_context":target_key==="building_exterior_context"?"evaluate_building_context":target_key==="condensate_context"?"evaluate_condensate_context":"evaluate_core_drilling_context"],required_views:["wide_overview"],minimum_count:1,maximum_count:1,dependency_keys:[],safety_constraints:safe})),
]);

export const EVIDENCE_BUNDLE_REGISTRY=Object.freeze([{bundle_key:"indoor_context_bundle" as const,target_keys:Object.freeze(["room_overview","indoor_area_overview"] as const),template_key:"evidence_indoor_context_bundle" as const},{bundle_key:"outdoor_context_bundle" as const,target_keys:Object.freeze(["outdoor_area_overview","accessibility_context"] as const)},{bundle_key:"installation_route_bundle" as const,target_keys:Object.freeze(["indoor_area_overview","outdoor_area_overview","line_route_context"] as const)}]);
export const DOCUMENT_EVIDENCE_TARGET_REGISTRY=Object.freeze([] as const);
export const INFORMATION_KEY_EVIDENCE_TARGETS=Object.freeze(Object.fromEntries(ALL_PROPERTY_KEYS.map(key=>[key,Object.freeze(EVIDENCE_TARGET_REGISTRY.filter(t=>t.supports_information_keys.includes(key)).map(t=>t.target_key))])) as Readonly<Record<PropertyKey,readonly EvidenceTargetKey[]>>);

export const EVIDENCE_REQUEST_TEMPLATES=Object.freeze({
 evidence_room_overview:"Bitte fotografiere den Raum einmal möglichst vollständig, sodass Wände, Fenster und Türen gut zu erkennen sind.",
 evidence_indoor_area_overview:"Bitte fotografiere den Bereich, an dem das Innengerät ungefähr hängen könnte. Nimm etwas Umgebung mit auf, damit Wand, Fenster und angrenzende Bereiche erkennbar sind.",
 evidence_outdoor_area_overview:"Bitte fotografiere den möglichen Bereich für das Außengerät mit etwas Umgebung. Betritt dafür bitte keine gefährlichen oder schwer zugänglichen Bereiche.",
 evidence_line_route_context:"Bitte fotografiere den Bereich zwischen möglicher Innenposition und der Außenwand beziehungsweise den angrenzenden Bereichen, soweit das sicher möglich ist.",
 evidence_electrical_area:"Wenn du weißt, wo sich in der Nähe ein möglicher Stromanschluss befindet, fotografiere bitte den Bereich. Bitte nichts öffnen oder verändern.",
 evidence_accessibility_context:"Bitte fotografiere den möglichen Montagebereich mit etwas Umgebung, damit die Zugänglichkeit später beurteilt werden kann. Benutze dafür bitte keine Leiter.",
 evidence_indoor_context_bundle:"Bitte fotografiere den Raum vollständig und zusätzlich den möglichen Bereich für das Innengerät mit etwas Umgebung.",
} satisfies Readonly<Record<typeof EVIDENCE_TEMPLATE_KEYS[number],string>>);
export const renderEvidenceRequest=(request:SelectedEvidenceRequest)=>Object.freeze({heading:"Foto benötigt" as const,text:EVIDENCE_REQUEST_TEMPLATES[request.template_key],purpose_codes:request.purpose_codes});
export const EVIDENCE_SIMULATOR_CONTROLS=Object.freeze(["Foto als vorhanden simulieren","Kann ich nicht liefern","Überspringen"] as const);

export type EvidencePlanningNeed=Readonly<{information_key:PropertyKey;entity_type:typeof ENTITY_TYPES[number];entity_id:string;open:boolean;collection_path:"future_photo_request"|"future_document_request"|"customer_question"|"customer_clarification"|"existing_evidence"|"assumption"|"site_check"|"human_review"|"leave_open"}>;
export type EvidencePlannerInput=Readonly<{project_id:string;conversation_id:string;request_id:string;needs:readonly EvidencePlanningNeed[];request_state:EvidenceRequestState;availability:readonly EvidenceAvailability[];available_dependency_keys:readonly PropertyKey[];human_review_required:boolean;site_check_authoritative:boolean;consecutive_evidence_requests:number;total_evidence_requests:number;explicit_revisit?:boolean}>;
export type EvidencePlannerResult=Readonly<{kind:"evidence_request_selected";request:SelectedEvidenceRequest;rendered:ReturnType<typeof renderEvidenceRequest>}|{kind:"no_evidence_request";reason:typeof NO_EVIDENCE_REQUEST_REASONS[number]}>;

export function planEvidenceRequest(input:EvidencePlannerInput):EvidencePlannerResult{
 const parsed=evidenceRequestStateSchema.safeParse(input.request_state);if(!parsed.success||parsed.data.project_id!==input.project_id||parsed.data.conversation_id!==input.conversation_id)return{kind:"no_evidence_request",reason:"collection_path_not_eligible"};
 if(input.human_review_required)return{kind:"no_evidence_request",reason:"human_review_required"};if(input.site_check_authoritative)return{kind:"no_evidence_request",reason:"site_check_authoritative"};
 const open=input.needs.filter(n=>n.open);if(open.some(n=>n.collection_path==="future_document_request"))return{kind:"no_evidence_request",reason:"document_request_deferred"};
 const photo=open.filter(n=>n.collection_path==="future_photo_request");if(!photo.length)return{kind:"no_evidence_request",reason:"collection_path_not_eligible"};
 if(input.consecutive_evidence_requests>=2||input.total_evidence_requests>=4)return{kind:"no_evidence_request",reason:"request_limit_reached"};
 const keys=new Set(photo.map(n=>n.information_key));const candidates=EVIDENCE_TARGET_REGISTRY.filter(t=>t.status==="active"&&t.supports_information_keys.some(k=>keys.has(k))&&t.dependency_keys.every(k=>input.available_dependency_keys.includes(k))).sort((a,b)=>b.supports_information_keys.filter(k=>keys.has(k)).length-a.supports_information_keys.filter(k=>keys.has(k)).length);
 const chosen=candidates.find(t=>!input.availability.some(a=>a.target_key===t.target_key&&["requested","available_unanalysed","analysed"].includes(a.status))&&!input.request_state.requests.some(r=>r.target_key===t.target_key&&(!input.explicit_revisit||["planned","requested","provided","declined","skipped"].includes(r.status))));
 if(!chosen)return{kind:"no_evidence_request",reason:candidates.length?"duplicate_request":"dependency_not_satisfied"};
 const covered=photo.filter(n=>chosen.supports_information_keys.includes(n.information_key)).map(n=>n.information_key);const indoorBundle=keys.has("room_area_sqm")&&keys.has("indoor_unit_position_known")&&chosen.target_key==="room_overview";const request=selectedEvidenceRequestSchema.parse({request_id:input.request_id,action_type:indoorBundle?"request_multiple_photos":"request_photo",target_key:chosen.target_key,...(indoorBundle?{bundle_key:"indoor_context_bundle"}:{}),information_keys:covered,purpose_codes:chosen.purpose_codes.filter((_,i)=>i<Math.max(1,covered.length)),template_key:indoorBundle?"evidence_indoor_context_bundle":chosen.template_key,required_views:chosen.required_views,minimum_count:indoorBundle?2:chosen.minimum_count,maximum_count:indoorBundle?3:chosen.maximum_count,request_reason_codes:["open_information_need","future_photo_path",...(covered.length>1?["covers_multiple_needs" as const]:[]),...(indoorBundle?["controlled_bundle" as const]:[])]});
 return{kind:"evidence_request_selected",request,rendered:renderEvidenceRequest(request)};
}

export function appendPlannedEvidenceRequest(state:EvidenceRequestState,request:SelectedEvidenceRequest,at:string):EvidenceRequestState{return evidenceRequestStateSchema.parse({...state,revision:state.revision+1,requests:[...state.requests,{request_id:request.request_id,target_key:request.target_key,...(request.bundle_key?{bundle_key:request.bundle_key}:{}),requested_for_information_keys:request.information_keys,purpose_codes:request.purpose_codes,status:"requested",attempts:1,requested_at:at}]});}
export function resolveSyntheticEvidenceRequest(state:EvidenceRequestState,requestId:string,outcome:"provided"|"declined"|"skipped",at:string):Readonly<{state:EvidenceRequestState;availability?:EvidenceAvailability}>{const requests=state.requests.map(r=>r.request_id===requestId?{...r,status:outcome,resolved_at:at}:r);const next=evidenceRequestStateSchema.parse({...state,revision:state.revision+1,requests});const item=next.requests.find(r=>r.request_id===requestId);return{state:next,...(outcome==="provided"&&item?{availability:evidenceAvailabilitySchema.parse({target_key:item.target_key,status:"available_unanalysed",request_id:item.request_id})}:{})};}
