import { questionTemplateSchema } from "./question-template-schemas";
import type { AnswerContract, AnswerOption, QuestionTemplate, QuestionTemplateLocale, QuestionTemplateRegistry } from "./question-template-types";

const option = (option_key: AnswerOption["option_key"], label: string): AnswerOption => ({ option_key, label, normalized_outcome: option_key });
const unknown = option("unknown", "Weiß ich nicht");
const skip = option("skip", "Möchte ich überspringen");
const textContract = (examples: readonly string[]): AnswerContract => ({ answer_type: "text", required: true, allows_unknown: true, allows_skip: true, min_length: 2, max_length: 100, options: [unknown, skip], examples, validation_error_code: "text_answer_invalid", maximum_attempts: 2 });
const boolContract: AnswerContract = { answer_type: "boolean", required: true, allows_unknown: true, allows_skip: true, options: [option("yes", "Ja"), option("no", "Nein"), unknown, skip], examples: [], validation_error_code: "boolean_answer_invalid", maximum_attempts: 2 };
const areaContract: AnswerContract = { answer_type: "approximate_number", required: true, allows_unknown: true, allows_skip: true, min_value: 5, max_value: 500, unit: "sqm", precision: 1, options: [unknown, skip], examples: ["25 m²", "etwa 20 bis 30 m²"], validation_error_code: "approximate_number_invalid", maximum_attempts: 2 };
const confirmationContract: AnswerContract = { answer_type: "boolean", required: true, allows_unknown: true, allows_skip: false, options: [option("confirm_assumption", "Ja, damit vorläufig weiterarbeiten"), option("reject_assumption", "Nein"), option("unknown", "Kann ich nicht einschätzen"), option("defer", "Später prüfen")], examples: [], validation_error_code: "confirmation_answer_invalid", maximum_attempts: 1 };
const base = { template_version: 1, locale: "de", examples: [], controlled_parameter_keys: [], customer_visible: true, status: "active" } as const;
const templates: QuestionTemplate[] = [
  { ...base, template_key: "ask_room_type", message_kind: "question", supported_action_type: "ask_text", supported_answer_type: "text", information_key: "room_type", primary_text: "Um welchen Raum geht es?", supporting_text: "Eine kurze Bezeichnung reicht.", examples: ["Wohnzimmer", "Schlafzimmer", "Büro"], answer_contract: textContract(["Wohnzimmer", "Schlafzimmer", "Büro"]) },
  { ...base, template_key: "ask_room_area_approximate", message_kind: "question", supported_action_type: "ask_approximate_number", supported_answer_type: "approximate_number", information_key: "room_area_sqm", primary_text: "Wie groß ist der Raum ungefähr?", supporting_text: "Eine grobe Schätzung reicht völlig.", help_text: "Du kannst zum Beispiel 25 m² oder etwa 20 bis 30 m² angeben.", examples: ["25 m²", "etwa 20 bis 30 m²"], answer_contract: areaContract, accessibility_text: "Wie groß ist der Raum ungefähr in Quadratmetern? Verfügbar sind auch Weiß ich nicht und Möchte ich überspringen." },
  { ...base, template_key: "ask_room_area_approximate_retry", message_kind: "question", supported_action_type: "ask_approximate_number", supported_answer_type: "approximate_number", information_key: "room_area_sqm", primary_text: "Kein Problem, eine grobe Raumgröße reicht.", help_text: "Du kannst dich an kleiner als 20 m², etwa 20 bis 30 m² oder größer orientieren und eine ungefähre Zahl angeben.", examples: ["15 m²", "25 m²", "35 m²"], answer_contract: areaContract, retry_variant_of: "ask_room_area_approximate", retry_attempt: 2 },
  { ...base, template_key: "ask_building_type", message_kind: "question", supported_action_type: "ask_text", supported_answer_type: "text", information_key: "building_type", primary_text: "Um welche Gebäudeart handelt es sich?", examples: ["Wohnung", "Einfamilienhaus", "Dachgeschosswohnung"], answer_contract: textContract(["Wohnung", "Einfamilienhaus", "Dachgeschosswohnung"]) },
  { ...base, template_key: "ask_indoor_position_known", message_kind: "question", supported_action_type: "ask_yes_no", supported_answer_type: "boolean", information_key: "indoor_unit_position_known", primary_text: "Hast du schon eine Idee, an welcher Wand das Innengerät hängen könnte?", supporting_text: "Deine Angabe ist noch keine technische Bestätigung.", answer_contract: boolContract },
  { ...base, template_key: "ask_outdoor_position_known", message_kind: "question", supported_action_type: "ask_yes_no", supported_answer_type: "boolean", information_key: "outdoor_unit_position_known", primary_text: "Weißt du schon, wo das Außengerät ungefähr stehen oder hängen könnte?", supporting_text: "Deine Angabe ist noch keine technische Bestätigung.", answer_contract: boolContract },
  { ...base, template_key: "ask_line_route_known", message_kind: "question", supported_action_type: "ask_yes_no", supported_answer_type: "boolean", information_key: "line_route_known", primary_text: "Ist ungefähr bekannt, wie die Leitungen vom Innen- zum Außengerät geführt werden könnten?", supporting_text: "Deine Angabe ist noch keine technische Bestätigung.", answer_contract: boolContract },
  { ...base, template_key: "ask_electrical_supply_known", message_kind: "question", supported_action_type: "ask_yes_no", supported_answer_type: "boolean", information_key: "electrical_supply_known", primary_text: "Weißt du, ob in der Nähe ein geeigneter Stromanschluss vorhanden ist?", supporting_text: "Deine Angabe ist noch keine technische Bestätigung.", answer_contract: boolContract },
  { ...base, template_key: "ask_accessibility_known", message_kind: "question", supported_action_type: "ask_yes_no", supported_answer_type: "boolean", information_key: "accessibility_known", primary_text: "Ist der geplante Montagebereich mit einer normalen Leiter gut erreichbar?", supporting_text: "Deine Angabe ist noch keine technische Bestätigung.", answer_contract: boolContract },
  { ...base, template_key: "confirm_room_area_assumption", message_kind: "confirmation", supported_action_type: "offer_assumption", supported_answer_type: "boolean", information_key: "room_area_sqm", primary_text: "Falls du die genaue Raumgröße nicht kennst, können wir vorläufig mit einer groben Raumgröße weiterarbeiten. Passt das ungefähr?", supporting_text: "Das bleibt als Annahme gekennzeichnet und kann später korrigiert werden.", controlled_parameter_keys: ["approximate_example"], answer_contract: confirmationContract },
  { ...base, template_key: "notice_line_route_site_check", message_kind: "notice", supported_action_type: "mark_requires_site_check", information_key: "line_route_known", primary_text: "Das lässt sich aus der Ferne nicht sicher beurteilen. Wir markieren den Leitungsweg für eine spätere Prüfung vor Ort." },
  { ...base, template_key: "notice_electrical_site_check", message_kind: "notice", supported_action_type: "mark_requires_site_check", information_key: "electrical_supply_known", primary_text: "Das lässt sich aus der Ferne nicht sicher beurteilen. Wir markieren den Stromanschluss für eine spätere Prüfung vor Ort." },
  { ...base, template_key: "notice_outdoor_position_site_check", message_kind: "notice", supported_action_type: "mark_requires_site_check", information_key: "outdoor_unit_position_known", primary_text: "Das lässt sich aus der Ferne nicht sicher beurteilen. Wir markieren die Außengeräteposition für eine spätere Prüfung vor Ort." },
  { ...base, template_key: "notice_accessibility_site_check", message_kind: "notice", supported_action_type: "mark_requires_site_check", information_key: "accessibility_known", primary_text: "Das lässt sich aus der Ferne nicht sicher beurteilen. Wir markieren die Zugänglichkeit für eine spätere Prüfung vor Ort." },
  { ...base, template_key: "internal_human_review", message_kind: "internal_notice", supported_action_type: "request_human_review", information_key: "room_area_sqm", primary_text: "Persönliche Prüfung erforderlich.", customer_visible: false },
  { ...base, template_key: "notice_human_review", message_kind: "notice", supported_action_type: "request_human_review", information_key: "room_area_sqm", primary_text: "Diesen Punkt möchten wir kurz persönlich prüfen. Wir melden uns dazu." },
  { ...base, template_key: "present_preliminary_assessment", message_kind: "intermediate_result", supported_action_type: "present_intermediate_result", information_key: "room_area_sqm", primary_text: "Hier ist der aktuelle Zwischenstand.", controlled_parameter_keys: ["assessment_level_label", "known_items", "assumption_items", "open_items", "next_step_label"] },
  { ...base, template_key: "end_collection_paused", message_kind: "collection_end", supported_action_type: "end_collection", information_key: "room_area_sqm", primary_text: "Wir haben den aktuellen Stand festgehalten und können später weitermachen." },
  { ...base, template_key: "end_collection_site_visit", message_kind: "collection_end", supported_action_type: "end_collection", information_key: "room_area_sqm", primary_text: "Für die offenen technischen Punkte ist eine Prüfung vor Ort sinnvoll." },
];

const deepFreeze = <T>(value: T): T => { if (value && typeof value === "object" && !Object.isFrozen(value)) { Object.freeze(value); Object.values(value).forEach(deepFreeze); } return value; };
export const QUESTION_TEMPLATE_REGISTRY: QuestionTemplateRegistry = deepFreeze(templates);
export function validateQuestionTemplateRegistry(registry: QuestionTemplateRegistry): boolean {
  const identities = new Set<string>();
  for (const template of registry) { if (!questionTemplateSchema.safeParse(template).success) return false; const identity = `${template.template_key}:${template.locale}:${template.template_version}`; if (identities.has(identity)) return false; identities.add(identity); }
  return true;
}
export function getQuestionTemplate(registry: QuestionTemplateRegistry, templateKey: string, locale: QuestionTemplateLocale, version: number): QuestionTemplate | undefined { return registry.find((item) => item.template_key === templateKey && item.locale === locale && item.template_version === version); }
export function listActiveQuestionTemplates(registry: QuestionTemplateRegistry = QUESTION_TEMPLATE_REGISTRY): readonly QuestionTemplate[] { return registry.filter((item) => item.status === "active"); }
