import { selectedNextActionSchema, type SelectedNextAction } from "./question-planner-schemas";
import type { PlannerActionType } from "./question-planner-types";
import type { PropertyKey } from "./types";
import type { RenderParameters } from "./question-template-types";

const score = { safety_relevance: 0, feasibility_impact: 0, sizing_impact: 0, installation_impact: 0, price_risk_impact: 0, readiness_impact: 0, expected_information_gain: 0, answerability: 0, customer_effort: 0, repetition_penalty: 0, contradiction_bonus: 0, dependency_bonus: 0, assumption_availability_penalty: 0, site_check_availability_penalty: 0, total: 0 };
export const syntheticTemplateAction = (template_key: SelectedNextAction["template_key"], action_type: PlannerActionType, information_key: PropertyKey, answer_type?: "text" | "boolean" | "approximate_number"): SelectedNextAction => selectedNextActionSchema.parse({ decision_id: "81000000-0000-4000-8000-000000000001", project_id: "81000000-0000-4000-8000-000000000002", conversation_id: "81000000-0000-4000-8000-000000000003", based_on_state_version: 1, selected_candidate_id: "81000000-0000-4000-8000-000000000004", action_type, information_key, entity_type: information_key === "building_type" ? "project" : "room", entity_id: "81000000-0000-4000-8000-000000000005", answer_contract: answer_type ? { answer_type } : undefined, template_key, template_version: 1, assumption_key: action_type === "offer_assumption" ? "rough_room_area_for_level_2" : undefined, fallback_paths: ["present_intermediate_result"], reason_codes: ["missing_for_target"], priority_band: "readiness_blocker", score_breakdown: score, created_at: "2026-08-06T10:00:00.000Z", created_by_actor_class: "system" });
export const SYNTHETIC_TEMPLATE_RENDER_FIXTURES = {
  roomArea: [syntheticTemplateAction("ask_room_area_approximate", "ask_approximate_number", "room_area_sqm", "approximate_number"), {}], retryRoomArea: [syntheticTemplateAction("ask_room_area_approximate_retry", "ask_approximate_number", "room_area_sqm", "approximate_number"), {}], roomType: [syntheticTemplateAction("ask_room_type", "ask_text", "room_type", "text"), {}], buildingType: [syntheticTemplateAction("ask_building_type", "ask_text", "building_type", "text"), {}], indoorPosition: [syntheticTemplateAction("ask_indoor_position_known", "ask_yes_no", "indoor_unit_position_known", "boolean"), {}], outdoorPosition: [syntheticTemplateAction("ask_outdoor_position_known", "ask_yes_no", "outdoor_unit_position_known", "boolean"), {}], lineRoute: [syntheticTemplateAction("ask_line_route_known", "ask_yes_no", "line_route_known", "boolean"), {}], electrical: [syntheticTemplateAction("ask_electrical_supply_known", "ask_yes_no", "electrical_supply_known", "boolean"), {}], accessibility: [syntheticTemplateAction("ask_accessibility_known", "ask_yes_no", "accessibility_known", "boolean"), {}], assumption: [syntheticTemplateAction("confirm_room_area_assumption", "offer_assumption", "room_area_sqm", "boolean"), { approximate_example: "25 m²" }], siteCheck: [syntheticTemplateAction("notice_line_route_site_check", "mark_requires_site_check", "line_route_known"), {}], internalReview: [syntheticTemplateAction("internal_human_review", "request_human_review", "room_area_sqm"), {}], visibleReview: [syntheticTemplateAction("notice_human_review", "request_human_review", "room_area_sqm"), {}], intermediate: [syntheticTemplateAction("present_preliminary_assessment", "present_intermediate_result", "room_area_sqm"), { assessment_level_label: "vorläufig", known_items: ["Raumart"], assumption_items: ["Raumgröße"], open_items: ["Leitungsweg"], next_step_label: "offene Punkte klären" }], paused: [syntheticTemplateAction("end_collection_paused", "end_collection", "room_area_sqm"), {}], siteVisit: [syntheticTemplateAction("end_collection_site_visit", "end_collection", "room_area_sqm"), {}],
} as const satisfies Record<string, readonly [SelectedNextAction, RenderParameters]>;
