import { projectClassLabels, projectClasses, projectStatuses, type ProjectClass, type ProjectStatus } from "@/lib/domain/types";
import { statusToLabel } from "@/lib/domain/mappers";
import { getAllowedStatusTransitions } from "@/lib/domain/project-status";
import { SubmitButton } from "./submit-button";

type CustomerFormProps = { action: (formData: FormData) => void | Promise<void>; customer?: { first_name: string; last_name: string; email: string | null; phone: string | null }; submitLabel: string };

export function CustomerForm({ action, customer, submitLabel }: CustomerFormProps) {
  return <form action={action} className="grid gap-4 md:grid-cols-2"><label className="space-y-1"><span>Vorname *</span><input name="first_name" required defaultValue={customer?.first_name} className="w-full rounded border p-2" /></label><label className="space-y-1"><span>Nachname *</span><input name="last_name" required defaultValue={customer?.last_name} className="w-full rounded border p-2" /></label><label className="space-y-1"><span>E-Mail</span><input name="email" type="email" defaultValue={customer?.email ?? ""} className="w-full rounded border p-2" /></label><label className="space-y-1"><span>Telefon</span><input name="phone" defaultValue={customer?.phone ?? ""} className="w-full rounded border p-2" /></label><SubmitButton className="md:col-span-2">{submitLabel}</SubmitButton></form>;
}

type ProjectFormProps = { action: (formData: FormData) => void | Promise<void>; customers: { id: string; first_name: string; last_name: string }[]; project?: { customer_id: string; title: string; status: ProjectStatus; project_class: ProjectClass | null; installation_address: string | null; postal_code: string | null; city: string | null; summary: string | null; requires_human_review: boolean }; role: "admin" | "reviewer"; submitLabel: string };

export function ProjectForm({ action, customers, project, role, submitLabel }: ProjectFormProps) {
  const isAdmin = role === "admin";
  const statusOptions = project ? [project.status, ...getAllowedStatusTransitions(project.status)] : projectStatuses;
  return <form action={action} className="grid gap-4 md:grid-cols-2"><label className="space-y-1"><span>Kunde *</span><select name="customer_id" required disabled={!isAdmin} defaultValue={project?.customer_id ?? ""} className="w-full rounded border p-2"><option value="">Kunde auswählen</option>{customers.map((customer) => <option key={customer.id} value={customer.id}>{customer.first_name} {customer.last_name}</option>)}</select></label><label className="space-y-1"><span>Titel *</span><input name="title" required disabled={!isAdmin} defaultValue={project?.title ?? ""} className="w-full rounded border p-2" /></label><label className="space-y-1"><span>Status</span><select name="status" defaultValue={project?.status ?? "new"} className="w-full rounded border p-2">{statusOptions.map((status) => <option key={status} value={status}>{statusToLabel(status)}</option>)}</select></label><label className="space-y-1"><span>Projektklasse</span><select name="project_class" defaultValue={project?.project_class ?? ""} className="w-full rounded border p-2"><option value="">Keine Klasse</option>{projectClasses.map((projectClass) => <option key={projectClass} value={projectClass}>{projectClassLabels[projectClass]}</option>)}</select></label><label className="space-y-1"><span>Installationsadresse</span><input name="installation_address" disabled={!isAdmin} defaultValue={project?.installation_address ?? ""} className="w-full rounded border p-2" /></label><label className="space-y-1"><span>Postleitzahl</span><input name="postal_code" disabled={!isAdmin} defaultValue={project?.postal_code ?? ""} className="w-full rounded border p-2" /></label><label className="space-y-1"><span>Ort</span><input name="city" disabled={!isAdmin} defaultValue={project?.city ?? ""} className="w-full rounded border p-2" /></label><label className="flex items-center gap-2"><input name="requires_human_review" type="checkbox" defaultChecked={project?.requires_human_review ?? true} value="true" /> Human Review erforderlich</label><label className="space-y-1 md:col-span-2"><span>Zusammenfassung</span><textarea name="summary" defaultValue={project?.summary ?? ""} className="min-h-32 w-full rounded border p-2" /></label><SubmitButton className="md:col-span-2">{submitLabel}</SubmitButton></form>;
}
