"use server";

import { revalidatePath } from "next/cache";
import { z } from "zod";
import { canManageKlimaGuyKnowledge } from "@/lib/domain/permissions";
import { klimaguyKnowledgeCategorySchema, klimaguyKnowledgeGuidanceSchema, klimaguyKnowledgePrioritySchema, klimaguyKnowledgeTitleSchema } from "@/lib/domain/klimaguy-knowledge";
import { roleSchema } from "@/lib/domain/schemas";
import { createClient } from "@/lib/supabase/server";

export type KlimaGuyKnowledgeActionState = { success: boolean; message: string };
const fields = z.object({ category: klimaguyKnowledgeCategorySchema, title: klimaguyKnowledgeTitleSchema, guidance: klimaguyKnowledgeGuidanceSchema, priority: z.coerce.number().pipe(klimaguyKnowledgePrioritySchema) }).strict();
async function adminClient() { const client=await createClient(); const { data:{user} }=await client.auth.getUser(); const {data:profile}=user?await client.from("profiles").select("role").eq("id",user.id).maybeSingle():{data:null}; const role=roleSchema.safeParse(profile?.role); return role.success&&canManageKlimaGuyKnowledge(role.data)?client:null; }
function message(error: unknown) { return error instanceof Error && (error.message.includes("stale") || ("code" in error && error.code==="40001")) ? "Der Eintrag wurde zwischenzeitlich geändert. Bitte lade die Seite neu." : "Die Änderung konnte nicht gespeichert werden."; }
export async function createKnowledgeAction(_state:KlimaGuyKnowledgeActionState,formData:FormData):Promise<KlimaGuyKnowledgeActionState>{ const parsed=fields.safeParse(Object.fromEntries(["category","title","guidance","priority"].map(k=>[k,formData.get(k)]))); if(!parsed.success)return{success:false,message:"Bitte prüfe die Eingaben."}; const client=await adminClient(); if(!client)return{success:false,message:"Nur Administratoren dürfen Wissen verwalten."}; const {error}=await client.rpc("create_klimaguy_knowledge_entry",{target_category:parsed.data.category,target_title:parsed.data.title,target_guidance:parsed.data.guidance,target_priority:parsed.data.priority}); if(error)return{success:false,message:message(error)}; revalidatePath("/admin/klimaguy/knowledge"); return{success:true,message:"Wissen wurde freigegeben."}; }
export async function updateKnowledgeAction(_state:KlimaGuyKnowledgeActionState,formData:FormData):Promise<KlimaGuyKnowledgeActionState>{ const parsed=fields.extend({id:z.string().uuid(),expected_revision:z.coerce.number().int().positive()}).safeParse(Object.fromEntries(formData)); if(!parsed.success)return{success:false,message:"Bitte prüfe die Eingaben."}; const client=await adminClient(); if(!client)return{success:false,message:"Nicht erlaubt."}; const {id,expected_revision,...value}=parsed.data; const {error}=await client.rpc("update_klimaguy_knowledge_entry",{target_id:id,target_expected_revision:expected_revision,target_category:value.category,target_title:value.title,target_guidance:value.guidance,target_priority:value.priority}); if(error)return{success:false,message:message(error)}; revalidatePath("/admin/klimaguy/knowledge"); return{success:true,message:"Wissen aktualisiert."}; }
export async function setKnowledgeStatusAction(formData:FormData){ const parsed=z.object({id:z.string().uuid(),expected_revision:z.coerce.number().int().positive(),status:z.enum(["active","archived"])}).safeParse(Object.fromEntries(formData)); const client=await adminClient(); if(parsed.success&&client) await client.rpc("set_klimaguy_knowledge_entry_status",{target_id:parsed.data.id,target_expected_revision:parsed.data.expected_revision,target_status:parsed.data.status}); revalidatePath("/admin/klimaguy/knowledge"); }
export async function reviewLearningAction(_state:KlimaGuyKnowledgeActionState,formData:FormData):Promise<KlimaGuyKnowledgeActionState>{ const base=z.object({id:z.string().uuid(),expected_revision:z.coerce.number().int().positive(),action:z.enum(["approve","reject"])}); const parsed=base.and(fields).safeParse(Object.fromEntries(formData)); if(!parsed.success)return{success:false,message:"Bitte prüfe die Eingaben."}; const client=await adminClient(); if(!client)return{success:false,message:"Nicht erlaubt."}; const {error}=await client.rpc("review_klimaguy_learning_candidate",{target_id:parsed.data.id,target_expected_revision:parsed.data.expected_revision,target_action:parsed.data.action,target_category:parsed.data.category,target_title:parsed.data.title,target_guidance:parsed.data.guidance,target_priority:parsed.data.priority}); if(error)return{success:false,message:message(error)}; revalidatePath("/admin/klimaguy/knowledge"); return{success:true,message:parsed.data.action==="approve"?"Learning wurde als Wissen freigegeben.":"Learning wurde abgelehnt."}; }
