-- AP-16-06-06D-21: accept only the fully proven D-18 recovery lineage during context reconstruction.
-- No rows are rewritten: already-rehabilitated production commands retain the original answer
-- and prompt, while their original effort state remains valid input authority.

create or replace function public.get_customer_message_cycle_context(target_command_id uuid) returns jsonb language plpgsql security definer set search_path=public,pg_temp as $$
declare cmd public.conversation_cycle_commands%rowtype; c public.conversations%rowtype; r public.conversation_runtime_states%rowtype; p public.conversation_pending_interactions%rowtype; m public.conversation_messages%rowtype; pm public.conversation_messages%rowtype; s public.conversation_interaction_snapshots%rowtype; original_p public.conversation_pending_interactions%rowtype; original_s public.conversation_interaction_snapshots%rowtype; body text; prompt_body text; rendered_outbound_text text; knowledge jsonb; collection jsonb; retry jsonb; effort jsonb; evidence_state jsonb; availability jsonb; context jsonb; effort_revision integer;
begin
 if auth.role() is distinct from 'service_role' then raise insufficient_privilege using message='customer_message_cycle_context_service_role_required'; end if;
 select * into cmd from public.conversation_cycle_commands where id=target_command_id;
 if not found then return jsonb_build_object('success',false,'code','command_not_found'); end if;
 if cmd.command_type<>'customer_answer' or cmd.status<>'processing' then return jsonb_build_object('success',false,'code','command_not_claimed'); end if;
 if cmd.project_id is null or cmd.prompt_message_id is null or cmd.execution_at is null or cmd.event_sequence_start is null or cardinality(cmd.event_ids)<>5 then return jsonb_build_object('success',false,'code','authority_incomplete'); end if;
 select * into c from public.conversations where id=cmd.conversation_id;
 if c.id is null or c.status<>'open' or c.revision<>cmd.expected_conversation_revision then return jsonb_build_object('success',false,'code','conversation_mismatch'); end if;
 if c.current_project_id is distinct from cmd.project_id then return jsonb_build_object('success',false,'code','project_mismatch'); end if;
 select * into r from public.conversation_runtime_states where conversation_id=cmd.conversation_id;
 if r.conversation_id is null or r.project_id<>cmd.project_id or r.revision<>cmd.expected_runtime_revision or r.runtime_status<>'awaiting_customer_answer' then return jsonb_build_object('success',false,'code','runtime_stale'); end if;
 if r.knowledge_state_version<>cmd.expected_knowledge_version or (select current_version from public.project_knowledge_states where project_id=cmd.project_id)<>cmd.expected_knowledge_version then return jsonb_build_object('success',false,'code','knowledge_stale'); end if;
 select * into p from public.conversation_pending_interactions where id=cmd.pending_interaction_id;
 if p.id is null then return jsonb_build_object('success',false,'code','pending_interaction_missing'); end if;
 if p.status<>'pending' or r.active_pending_interaction_id<>p.id or p.conversation_id<>cmd.conversation_id or p.project_id<>cmd.project_id or p.runtime_revision<>cmd.expected_runtime_revision or p.expected_knowledge_state_version<>cmd.expected_knowledge_version or p.prompt_message_id<>cmd.prompt_message_id then return jsonb_build_object('success',false,'code','pending_interaction_stale'); end if;
 if p.snapshot_id is null then return jsonb_build_object('success',false,'code','snapshot_missing'); end if;
 select * into s from public.conversation_interaction_snapshots where id=p.snapshot_id and pending_interaction_id=p.id;
 if s.id is null then return jsonb_build_object('success',false,'code','snapshot_missing'); end if;
 rendered_outbound_text:=concat_ws(E'\n\n',s.rendered_interaction->>'primary_text',s.rendered_interaction->>'supporting_text',s.rendered_interaction->>'help_text');
 select * into m from public.conversation_messages where id=cmd.source_message_id; select mt.body into body from public.conversation_message_text mt where mt.message_id=m.id;
 if m.id is null or body is null or m.conversation_id<>cmd.conversation_id or m.direction<>'inbound' or m.actor_class<>'customer' or m.message_kind<>'text' then return jsonb_build_object('success',false,'code','source_message_invalid'); end if;
 select * into pm from public.conversation_messages where id=cmd.prompt_message_id; select mt.body into prompt_body from public.conversation_message_text mt where mt.message_id=pm.id;
 if pm.id is null or pm.conversation_id<>cmd.conversation_id or pm.direction<>'outbound' or pm.actor_class not in ('system','ai') or pm.message_kind<>'text' or pm.sequence<>s.outbound_message_sequence or s.outbound_message_id<>pm.id or prompt_body<>rendered_outbound_text or m.sequence<=pm.sequence then return jsonb_build_object('success',false,'code','prompt_message_mismatch'); end if;
 if s.conversation_id<>cmd.conversation_id or s.project_id<>cmd.project_id or s.runtime_revision<>cmd.expected_runtime_revision or s.knowledge_state_version<>cmd.expected_knowledge_version then return jsonb_build_object('success',false,'code','snapshot_invalid'); end if;

 -- A normal cycle owns effort state at its execution revision. D-18 necessarily moved
 -- runtime by two revisions (human review, then recovery) but D-18/D-20 selected the
 -- already advanced human-review revision and therefore moved no effort row.
 effort_revision:=cmd.expected_runtime_revision;
 if cmd.legacy_ai_exhaustion_rehabilitated_at is not null then
  if cmd.inference_semantics_version<>2 or p.recovery_of_pending_interaction_id is null or s.recovery_of_snapshot_id is null then return jsonb_build_object('success',false,'code','pending_interaction_stale'); end if;
  select * into original_p from public.conversation_pending_interactions where id=p.recovery_of_pending_interaction_id;
  select * into original_s from public.conversation_interaction_snapshots where id=s.recovery_of_snapshot_id;
  if original_p.id is null or original_p.status<>'answered' or original_p.answered_by_message_id is distinct from cmd.source_message_id or original_p.conversation_id<>cmd.conversation_id or original_p.project_id<>cmd.project_id or original_p.prompt_message_id<>cmd.prompt_message_id or original_p.runtime_revision<>cmd.expected_runtime_revision-2 or original_p.expected_knowledge_state_version<>cmd.expected_knowledge_version or original_p.snapshot_id<>original_s.id then return jsonb_build_object('success',false,'code','source_message_invalid'); end if;
  if original_s.id is null or original_s.pending_interaction_id<>original_p.id or original_s.conversation_id<>cmd.conversation_id or original_s.project_id<>cmd.project_id or original_s.runtime_revision<>original_p.runtime_revision or original_s.knowledge_state_version<>cmd.expected_knowledge_version or original_s.outbound_message_id<>cmd.prompt_message_id or s.recovery_of_snapshot_id<>original_s.id then return jsonb_build_object('success',false,'code','snapshot_invalid'); end if;
  if exists(select 1 from public.conversation_messages newer where newer.conversation_id=cmd.conversation_id and newer.direction='inbound' and newer.actor_class='customer' and newer.sequence>m.sequence) then return jsonb_build_object('success',false,'code','source_message_invalid'); end if;
  if not exists(select 1 from public.conversation_effort_states e where e.conversation_id=cmd.conversation_id and e.project_id=cmd.project_id and e.runtime_revision=effort_revision) then effort_revision:=original_p.runtime_revision; end if;
 end if;

 select jsonb_build_object('project_id',ks.project_id,'conversation_id',cmd.conversation_id,'state_version',ks.current_version,'claims',coalesce((select jsonb_agg(jsonb_strip_nulls(jsonb_build_object('claim_id',kc.claim_id,'project_id',kc.project_id,'entity_type',kc.entity_type,'entity_id',kc.entity_id,'property_key',kc.property_key,'value_type',kc.value_type,'value',case kc.value_type when 'string' then to_jsonb(kc.value_text) when 'number' then to_jsonb(kc.value_number) when 'boolean' then to_jsonb(kc.value_boolean) else 'null'::jsonb end,'epistemic_status',kc.epistemic_status,'knowledge_strength',kc.knowledge_strength,'supersedes_claim_id',kc.supersedes_claim_id,'evidence',(select jsonb_agg(jsonb_build_object('evidence_id',ke.id,'source_type',ke.source_type,'source_id',ke.evidence_id,'actor_class',ke.actor_class,'observed_at',ke.observed_at,'evidence_status',ke.evidence_status)) from public.project_knowledge_claim_evidence ke where ke.claim_id=kc.claim_id),'created_at',kc.created_at,'state_version',kc.claim_state_version))) from public.project_knowledge_claims kc where kc.knowledge_state_id=ks.id),'[]'::jsonb),'updated_at',ks.updated_at) into knowledge from public.project_knowledge_states ks where ks.project_id=cmd.project_id;
 select jsonb_build_object('project_id',cmd.project_id,'conversation_id',cmd.conversation_id,'version',coalesce(max(collection_version),0),'items',coalesce(jsonb_agg(jsonb_strip_nulls(jsonb_build_object('information_key',information_key,'entity_type',entity_type,'entity_id',entity_id,'collection_status',collection_status,'last_answer_meaning',last_answer_meaning,'attempts',attempts,'evidence_requirement',evidence_requirement,'revisit_status',revisit_status,'last_dependency_signature',dependency_signature,'last_collection_path',last_collection_path,'last_gain_reason',last_gain_reason,'updated_at',updated_at))) filter(where conversation_id is not null),'[]'::jsonb),'updated_at',coalesce(max(updated_at),r.updated_at)) into collection from public.conversation_information_collection where conversation_id=cmd.conversation_id;
 select jsonb_build_object('project_id',cmd.project_id,'conversation_id',cmd.conversation_id,'items',coalesce(jsonb_agg(jsonb_strip_nulls(jsonb_build_object('information_key',information_key,'entity_type',entity_type,'entity_id',entity_id,'attempts',attempts,'last_outcome',last_outcome,'last_attempt_at',last_attempt_at))) filter(where conversation_id is not null),'[]'::jsonb),'updated_at',coalesce(max(last_attempt_at),r.updated_at)) into retry from public.conversation_retry_states where conversation_id=cmd.conversation_id;
 select jsonb_strip_nulls(jsonb_build_object('consecutive_technical_questions',consecutive_technical_questions,'unanswered_questions',unanswered_questions,'repeated_questions',repeated_questions,'last_break_at',last_break_at)) into effort from public.conversation_effort_states where conversation_id=cmd.conversation_id and project_id=cmd.project_id and runtime_revision=effort_revision;
 select jsonb_build_object('project_id',cmd.project_id,'conversation_id',cmd.conversation_id,'requests',coalesce(jsonb_agg(jsonb_strip_nulls(jsonb_build_object('request_id',request_id,'target_key',target_key,'bundle_key',bundle_key,'requested_for_information_keys',requested_information_keys,'purpose_codes',purpose_codes,'status',status,'attempts',attempts,'requested_at',requested_at,'resolved_at',resolved_at))) filter(where request_id is not null),'[]'::jsonb),'revision',coalesce(max(evidence_revision),0)) into evidence_state from public.conversation_evidence_request_states where conversation_id=cmd.conversation_id;
 select coalesce(jsonb_agg(jsonb_build_object('target_key',target_key,'status',case when status='provided' then 'available_unanalysed' else 'requested' end,'request_id',request_id,'evidence_id',case when status='provided' then request_id else null end)) filter(where status in ('requested','provided')),'[]'::jsonb) into availability from public.conversation_evidence_request_states where conversation_id=cmd.conversation_id;
 if knowledge is null or effort is null then return jsonb_build_object('success',false,'code','authority_incomplete'); end if;
 context:=jsonb_build_object('cycle_id',cmd.id,'correlation_id',cmd.correlation_id,'project_id',cmd.project_id,'conversation_id',cmd.conversation_id,'knowledge_state',knowledge,'information_collection_state',collection,'retry_state',retry,'customer_effort_state',effort,'evidence_request_state',evidence_state,'evidence_availability',availability,'next_evidence_request_id',cmd.next_evidence_request_id,'interpretation_inputs',jsonb_build_object('interpretation_id',cmd.interpretation_id,'selected_action',s.selected_action,'rendered_interaction',s.rendered_interaction,'source_message_id',m.id,'source_actor_class','customer','interpreted_at',cmd.execution_at,'idempotency_key','answer:'||m.id,'proposal_ids',jsonb_build_object('transition_id',cmd.transition_id,'claim_id',cmd.claim_id,'customer_evidence_id',cmd.customer_evidence_id,'system_evidence_id',cmd.system_evidence_id)),'expected_state_version',cmd.expected_knowledge_version,'next_state_ids',jsonb_build_object('apply_id',cmd.apply_id),'event_ids',to_jsonb(cmd.event_ids),'event_sequence_start',cmd.event_sequence_start,'occurred_at',cmd.execution_at,'assessment_id',cmd.assessment_id,'planner_decision_id',cmd.planner_decision_id,'planner_candidate_ids','[]'::jsonb,'template_version',(s.rendered_interaction->>'template_version')::integer,'locale',s.rendered_interaction->>'locale');
 return jsonb_build_object('success',true,'command',jsonb_build_object('id',cmd.id,'conversation_id',cmd.conversation_id,'project_id',cmd.project_id,'source_message_id',cmd.source_message_id,'pending_interaction_id',cmd.pending_interaction_id,'expected_runtime_revision',cmd.expected_runtime_revision,'expected_knowledge_version',cmd.expected_knowledge_version,'execution_at',cmd.execution_at,'correlation_id',cmd.correlation_id,'interpretation_id',cmd.interpretation_id,'transition_id',cmd.transition_id,'claim_id',cmd.claim_id,'customer_evidence_id',cmd.customer_evidence_id,'system_evidence_id',cmd.system_evidence_id,'apply_id',cmd.apply_id,'assessment_id',cmd.assessment_id,'planner_decision_id',cmd.planner_decision_id,'event_ids',cmd.event_ids,'next_evidence_request_id',cmd.next_evidence_request_id,'next_pending_interaction_id',cmd.next_pending_interaction_id,'next_snapshot_id',cmd.next_snapshot_id,'next_outbound_message_id',cmd.next_outbound_message_id,'event_sequence_start',cmd.event_sequence_start),'source_message',jsonb_build_object('id',m.id,'conversation_id',m.conversation_id,'sequence',m.sequence,'direction',m.direction,'actor_class',m.actor_class,'message_kind',m.message_kind,'occurred_at',m.occurred_at,'text',body),'pending_interaction',jsonb_build_object('id',p.id,'conversation_id',p.conversation_id,'project_id',p.project_id,'status',p.status,'runtime_revision',p.runtime_revision,'expected_knowledge_state_version',p.expected_knowledge_state_version,'prompt_message_id',p.prompt_message_id,'snapshot_id',p.snapshot_id),'snapshot',jsonb_build_object('id',s.id,'pending_interaction_id',s.pending_interaction_id,'conversation_id',s.conversation_id,'project_id',s.project_id,'runtime_revision',s.runtime_revision,'knowledge_state_version',s.knowledge_state_version,'outbound_message_id',s.outbound_message_id,'outbound_message_sequence',s.outbound_message_sequence,'snapshot_schema_version',s.snapshot_schema_version,'selected_action',s.selected_action,'rendered_interaction',s.rendered_interaction,'outbound_text',rendered_outbound_text,'created_at',s.created_at),'cycle_context',context);
end $$;

revoke all on function public.get_customer_message_cycle_context(uuid) from public,anon,authenticated;
grant execute on function public.get_customer_message_cycle_context(uuid) to service_role;
comment on function public.get_customer_message_cycle_context(uuid) is 'Service-only context authority read with strict normal or D-18 recovery-lineage reconstruction.';
