"use client";
import Link from "next/link";
import { useActionState } from "react";
import { createKnowledgeAction, reviewLearningAction, setKnowledgeStatusAction, updateKnowledgeAction, type KlimaGuyKnowledgeActionState } from "@/lib/actions/klimaguy-knowledge";
import { KLIMAGUY_KNOWLEDGE_CATEGORIES, KLIMAGUY_KNOWLEDGE_CATEGORY_LABELS, type KlimaGuyKnowledgeEntry, type KlimaGuyLearningCandidate } from "@/lib/domain/klimaguy-knowledge";
import { Button, Card } from "@/components/ui";
const initial:KlimaGuyKnowledgeActionState={success:false,message:""}; const input="mt-1 w-full rounded-lg border border-slate-300 px-3 py-2";
function Fields({value}:{value?:{category:string;title:string;guidance:string;priority:number}}){return <div className="grid gap-3"><label>Kategorie<select name="category" defaultValue={value?.category??"customer_communication"} className={input}>{KLIMAGUY_KNOWLEDGE_CATEGORIES.map(c=><option key={c} value={c}>{KLIMAGUY_KNOWLEDGE_CATEGORY_LABELS[c]}</option>)}</select></label><label>Titel<input name="title" required minLength={3} maxLength={120} defaultValue={value?.title} className={input}/></label><label>Allgemeine Guidance<textarea name="guidance" required minLength={10} maxLength={800} rows={4} defaultValue={value?.guidance} className={input}/></label><label>Priorität (0–100)<input name="priority" type="number" min={0} max={100} defaultValue={value?.priority??50} className={input}/></label></div>}
function Manual(){const[state,action,pending]=useActionState(createKnowledgeAction,initial);return <Card><h2 className="text-xl font-bold">Neues manuelles Wissen</h2><p className="mb-4 text-sm text-slate-600">Wird erst durch dein ausdrückliches Speichern aktiv.</p><form action={action} className="space-y-4"><Fields/><Button disabled={pending}>Als aktives Wissen speichern</Button>{state.message&&<p role="status" className="text-sm">{state.message}</p>}</form></Card>}
function Entry({entry}:{entry:KlimaGuyKnowledgeEntry}){const[state,action,pending]=useActionState(updateKnowledgeAction,initial);return <Card className={entry.status==="archived"?"opacity-70":""}><div className="flex justify-between gap-3"><div><p className="text-xs font-bold uppercase text-teal-700">✓ Freigegebenes KlimaGuy-Wissen · {KLIMAGUY_KNOWLEDGE_CATEGORY_LABELS[entry.category]}</p><h3 className="text-lg font-bold">{entry.title}</h3></div><span>{entry.status==="active"?"Aktiv":"Archiviert"}</span></div><form action={action} className="mt-4 space-y-3"><input type="hidden" name="id" value={entry.id}/><input type="hidden" name="expected_revision" value={entry.revision}/><Fields value={entry}/><Button disabled={pending}>Änderungen speichern</Button>{state.message&&<p role="status" className="text-sm">{state.message}</p>}</form><form action={setKnowledgeStatusAction} className="mt-3"><input type="hidden" name="id" value={entry.id}/><input type="hidden" name="expected_revision" value={entry.revision}/><input type="hidden" name="status" value={entry.status==="active"?"archived":"active"}/><button className="text-sm font-semibold text-teal-800 underline">{entry.status==="active"?"Archivieren":"Reaktivieren"}</button></form><p className="mt-3 text-xs text-slate-500">Quelle: {entry.source_type==="manual"?"Manuell":"Aus Learning"} · zuletzt aktualisiert {new Date(entry.updated_at).toLocaleString("de-DE")}</p></Card>}
function Candidate({candidate}:{candidate:KlimaGuyLearningCandidate}){const[state,action,pending]=useActionState(reviewLearningAction,initial);return <Card className="border-amber-300 bg-amber-50"><p className="font-bold text-amber-900">⚠ Learning Candidate – noch nicht aktiv</p><h3 className="mt-1 text-lg font-bold">{candidate.title}</h3><p className="mt-2">{candidate.proposed_guidance}</p><p className="mt-2 text-sm text-slate-600"><strong>Warum:</strong> {candidate.rationale}</p><p className="mt-2 text-xs">{candidate.occurrence_count}× beobachtet · erstellt {new Date(candidate.created_at).toLocaleString("de-DE")} · zuletzt {new Date(candidate.updated_at).toLocaleString("de-DE")}</p><Link className="mt-2 inline-block text-sm font-semibold text-teal-800 underline" href={`/projects/${candidate.source_project_id}#conversation`}>Quelle im Projekt ansehen</Link><details className="mt-4"><summary className="cursor-pointer font-semibold">Prüfen</summary><form action={action} className="mt-3 space-y-3"><input type="hidden" name="id" value={candidate.id}/><input type="hidden" name="expected_revision" value={candidate.revision}/><Fields value={{category:candidate.category,title:candidate.title,guidance:candidate.proposed_guidance,priority:50}}/><div className="flex gap-3"><Button name="action" value="approve" disabled={pending}>Freigeben</Button><button name="action" value="reject" className="rounded-lg border px-4 py-2 font-semibold">Ablehnen</button></div>{state.message&&<p role="status">{state.message}</p>}</form></details></Card>}
export function KnowledgeManager({entries,candidates}:{entries:KlimaGuyKnowledgeEntry[];candidates:KlimaGuyLearningCandidate[]}){return <div className="space-y-8"><header><Link href="/admin/klimaguy" className="text-sm text-teal-700 underline">← KlimaGuy Operations</Link><p className="mt-4 text-sm font-bold uppercase tracking-wider text-teal-700">Administration</p><h1 className="text-3xl font-bold">Wissensbasis &amp; Learnings</h1><p className="mt-2 max-w-3xl text-slate-600">Operations steuert, wie KlimaGuy kommuniziert. Hier wird ausschließlich freigegeben, welches allgemeine Fach- und Verhaltenswissen er nutzen darf.</p></header><Manual/><section><h2 className="text-2xl font-bold">Freigegebenes Wissen</h2><div className="mt-4 grid gap-4">{entries.length?entries.map(e=><Entry key={e.id} entry={e}/>):<Card>Noch kein Wissen hinterlegt.</Card>}</div></section><section><div className="flex items-center gap-3"><h2 className="text-2xl font-bold">Learning Inbox</h2><span className="rounded-full bg-amber-200 px-3 py-1 font-bold">{candidates.length} offen</span></div><div className="mt-4 grid gap-4">{candidates.length?candidates.map(c=><Candidate key={c.id} candidate={c}/>):<Card>Keine offenen Learning Candidates.</Card>}</div></section></div>}
