"use client";

import Link from "next/link";
import { useActionState } from "react";
import { updateKlimaGuySettingsAction, type KlimaGuySettingsActionState } from "@/lib/actions/klimaguy-agent-settings";
import { KLIMAGUY_SETTINGS_OPTIONS, type EffectiveKlimaGuyAgentSettings, type KlimaGuyAgentSettings } from "@/lib/domain/klimaguy-agent-settings";
import { Button, Card } from "@/components/ui";

const initial: KlimaGuySettingsActionState = { success: false, message: "" };
const selectClasses = "mt-2 w-full rounded-lg border border-slate-300 bg-white px-3 py-2 text-slate-900 focus:border-teal-600 focus:outline-none focus:ring-2 focus:ring-teal-200";
function SelectField({ name, label, value, help }: { name: keyof KlimaGuyAgentSettings; label: string; value: string; help?: string }) {
  const options = KLIMAGUY_SETTINGS_OPTIONS[name as keyof typeof KLIMAGUY_SETTINGS_OPTIONS];
  return <label className="block text-sm font-medium text-slate-800">{label}<select className={selectClasses} name={name} defaultValue={value}>{options?.map((option) => <option key={option.value} value={option.value}>{option.label}</option>)}</select>{help ? <span className="mt-1 block text-xs text-slate-500">{help}</span> : null}</label>;
}
function Toggle({ name, label, checked, help }: { name: string; label: string; checked: boolean; help?: string }) {
  return <label className="flex gap-3 rounded-lg border border-slate-200 p-3"><input className="mt-1 h-4 w-4 accent-teal-700" type="checkbox" name={name} defaultChecked={checked} /><span><span className="block text-sm font-medium text-slate-800">{label}</span>{help ? <span className="block text-xs text-slate-500">{help}</span> : null}</span></label>;
}
export function KlimaGuyOperationsForm({ effective, canManage }: { effective: EffectiveKlimaGuyAgentSettings; canManage: boolean }) {
  const [state, action, pending] = useActionState(updateKlimaGuySettingsAction, initial);
  const s = effective.settings;
  const updated = effective.updatedAt ? new Intl.DateTimeFormat("de-DE", { dateStyle: "medium", timeStyle: "short", timeZone: "Europe/Berlin" }).format(new Date(effective.updatedAt)) : "noch nicht gespeichert – sichere Standardwerte aktiv";
  return <div className="space-y-6"><header className="flex flex-wrap items-end justify-between gap-4"><div><p className="text-sm font-semibold uppercase tracking-wider text-teal-700">Administration</p><h1 className="text-3xl font-bold text-slate-950">KlimaGuy Operations</h1><p className="mt-2 max-w-2xl text-slate-600">Steuere Persönlichkeit und sichere Gesprächsstrategie – ohne Geschäftsregeln oder technische Wahrheit zu verändern.</p></div><div className="flex flex-col items-end gap-2"><Link className="rounded-lg bg-teal-700 px-4 py-2 text-sm font-semibold text-white" href="/admin/klimaguy/knowledge">Wissensbasis &amp; Learnings</Link><Link className="text-sm font-medium text-teal-700 underline" href="/admin/intelligence/simulator">Conversation Simulator (Debug/Test)</Link></div></header>
    <form key={effective.revision} action={action} className="space-y-6"><input type="hidden" name="expected_revision" value={effective.revision} />
      <div className="grid gap-6 lg:grid-cols-2"><Card><h2 className="text-xl font-semibold">Kommunikation</h2><p className="mb-5 text-sm text-slate-500">So klingt KlimaGuy in neuen Antworten.</p><div className="grid gap-4 sm:grid-cols-2"><SelectField name="communication_formality" label="Anrede" value={s.communication_formality} help="Bleibt während des Gesprächs konsistent."/><SelectField name="tone" label="Ton" value={s.tone}/><SelectField name="response_length" label="Antwortlänge" value={s.response_length}/><SelectField name="emoji_usage" label="Emojis" value={s.emoji_usage}/><SelectField name="question_strategy" label="Fragen" value={s.question_strategy}/><SelectField name="greeting_style" label="Begrüßung" value={s.greeting_style}/><SelectField name="closing_style" label="Abschluss" value={s.closing_style}/><Toggle name="acknowledge_answers" label="Antworten bestätigen" checked={s.acknowledge_answers} help="Kurze natürliche Bestätigung, wenn sie hilfreich ist."/></div></Card>
      <div className="space-y-6"><Card><h2 className="text-xl font-semibold">Kundenhandling</h2><div className="mt-4 space-y-4"><Toggle name="ask_customer_name" label="Namen aktiv erfragen" checked={s.ask_customer_name} help="Der Name ist keine Voraussetzung für Angebotsbereitschaft."/><SelectField name="customer_name_timing" label="Zeitpunkt der Namensfrage" value={s.customer_name_timing}/><Toggle name="use_customer_name" label="Bekannten Namen verwenden" checked={s.use_customer_name} help="Natürlich und sparsam, nicht in jeder Nachricht."/></div></Card>
      <Card><h2 className="text-xl font-semibold">Qualifikationsverhalten</h2><p className="mb-4 text-sm text-slate-500">Ändert nur die Kommunikation, nie Readiness oder Pflichtangaben.</p><div className="space-y-4"><SelectField name="photo_request_strategy" label="Fotoanfrage" value={s.photo_request_strategy}/><SelectField name="unknown_answer_behavior" label="Unklare Antworten" value={s.unknown_answer_behavior}/><SelectField name="site_visit_policy" label="Vor-Ort-Prüfung" value={s.site_visit_policy}/></div></Card></div></div>
      <Card className="border-amber-200 bg-amber-50"><h2 className="text-xl font-semibold text-slate-950">Sicherheits- &amp; Geschäftsgrenzen</h2><p className="mt-1 text-sm text-slate-600">Fest im System verankert und nicht konfigurierbar.</p><ul className="mt-4 grid gap-2 text-sm font-medium text-slate-800 sm:grid-cols-2">{["Keine Preise durch KlimaGuy","Keine automatische Angebotsfreigabe","Kein automatischer Angebotsversand","Keine erfundene technische Gewissheit","Bilder ersetzen keine technische Prüfung","Vor-Ort-Prüfungen werden nicht als durchgeführt behauptet"].map((rule)=><li key={rule}>🔒 {rule}</li>)}</ul></Card>
      <div className="sticky bottom-4 flex flex-wrap items-center justify-between gap-4 rounded-xl border bg-white/95 p-4 shadow-lg backdrop-blur"><div><p className="text-sm text-slate-600">Konfiguration zuletzt aktualisiert: {updated}</p>{state.message ? <p role="status" className={`text-sm font-medium ${state.success ? "text-emerald-700" : "text-red-700"}`}>{state.message}</p> : null}</div>{canManage ? <Button type="submit" disabled={pending}>{pending ? "Speichert …" : "Änderungen speichern"}</Button> : <p className="text-sm font-medium text-slate-600">Nur Administratoren können Änderungen speichern.</p>}</div>
    </form></div>;
}
